/**
 * @vitest-environment happy-dom
 *
 * Snapshot lock for the Land-Brief markdown renderer. Pinned against
 * MTC_PROJECT so any change to the DiagnoseBrief schema or fixture must
 * explicitly accept the new brief output. The "Generated by Atlas on …"
 * footer is date-dependent and stripped before snapshotting.
 */

import { afterEach, describe, expect, it, vi } from "vitest";
import {
  downloadDiagnoseBrief,
  renderDiagnoseBriefMarkdown,
} from "../exportDiagnoseBrief.js";
import { MTC_PROJECT } from "../../data/mockProject.js";
import type { Project } from "../../types.js";

function stripFooterDate(md: string): string {
  return md.replace(
    /_Generated by Atlas on \d{4}-\d{2}-\d{2}\._/,
    "_Generated by Atlas on YYYY-MM-DD._",
  );
}

describe("renderDiagnoseBriefMarkdown — MTC fixture", () => {
  it("matches the pinned brief snapshot", () => {
    const md = stripFooterDate(renderDiagnoseBriefMarkdown(MTC_PROJECT));
    expect(md).toMatchSnapshot();
  });

  it("starts with the project name as H1 and ends with the dated footer", () => {
    const md = renderDiagnoseBriefMarkdown(MTC_PROJECT);
    expect(md.startsWith(`# ${MTC_PROJECT.name} — Land Brief`)).toBe(true);
    expect(md).toMatch(/_Generated by Atlas on \d{4}-\d{2}-\d{2}\._/);
  });

  it("emits one section per category in fixture order", () => {
    const md = renderDiagnoseBriefMarkdown(MTC_PROJECT);
    const headings = md.match(/^### .+$/gm) ?? [];
    expect(headings).toHaveLength(MTC_PROJECT.diagnose!.categories.length);
    MTC_PROJECT.diagnose!.categories.forEach((c, i) => {
      expect(headings[i]).toBe(`### ${c.title} — ${c.statusLabel}`);
    });
  });

  it("includes Risks / Opportunities / Limitations sections when each kind has items", () => {
    const md = renderDiagnoseBriefMarkdown(MTC_PROJECT);
    const kinds: Array<["Risks" | "Opportunities" | "Limitations", "risk" | "opportunity" | "limitation"]> = [
      ["Risks", "risk"],
      ["Opportunities", "opportunity"],
      ["Limitations", "limitation"],
    ];
    for (const [label, kind] of kinds) {
      const has = MTC_PROJECT.diagnose!.insights.some((i) => i.kind === kind);
      if (has) expect(md).toContain(`## ${label}`);
    }
  });
});

describe("renderDiagnoseBriefMarkdown — edge cases", () => {
  it("returns a no-brief stub when project.diagnose is missing", () => {
    const stub = { ...MTC_PROJECT, diagnose: undefined } as unknown as Project;
    const md = renderDiagnoseBriefMarkdown(stub);
    expect(md).toBe(`# ${MTC_PROJECT.name}\n\nNo land brief available.\n`);
  });

  it("renders a category without categoryDetails (no what's-happening triplet)", () => {
    const sliced: Project = {
      ...MTC_PROJECT,
      diagnose: { ...MTC_PROJECT.diagnose!, categoryDetails: undefined },
    };
    const md = renderDiagnoseBriefMarkdown(sliced);
    expect(md).not.toContain("**What's happening.**");
    expect(md).not.toContain("**What's wrong.**");
    expect(md).not.toContain("**What next.**");
    // Category headers and "What this means" lines still emit.
    expect(md).toContain("> _What this means:_");
  });

  it("omits an insight section when its kind has no items", () => {
    const sliced: Project = {
      ...MTC_PROJECT,
      diagnose: {
        ...MTC_PROJECT.diagnose!,
        insights: MTC_PROJECT.diagnose!.insights.filter((i) => i.kind !== "limitation"),
      },
    };
    const md = renderDiagnoseBriefMarkdown(sliced);
    expect(md).not.toContain("## Limitations");
    expect(md).toContain("## Risks");
  });
});

describe("downloadDiagnoseBrief", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("triggers a download with `<shortLabel>-land-brief.md` and revokes the blob URL", () => {
    const createObjectURL = vi.fn(() => "blob:mock-url");
    const revokeObjectURL = vi.fn();
    const originalCreate = URL.createObjectURL;
    const originalRevoke = URL.revokeObjectURL;
    URL.createObjectURL = createObjectURL as unknown as typeof URL.createObjectURL;
    URL.revokeObjectURL = revokeObjectURL as unknown as typeof URL.revokeObjectURL;
    vi.useFakeTimers();

    const clickSpy = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    try {
      downloadDiagnoseBrief(MTC_PROJECT);
      expect(createObjectURL).toHaveBeenCalledTimes(1);
      const blob = createObjectURL.mock.calls[0]?.[0] as Blob;
      expect(blob.type).toBe("text/markdown;charset=utf-8");
      expect(clickSpy).toHaveBeenCalledTimes(1);
      vi.runAllTimers();
      expect(revokeObjectURL).toHaveBeenCalledWith("blob:mock-url");
    } finally {
      URL.createObjectURL = originalCreate;
      URL.revokeObjectURL = originalRevoke;
      vi.useRealTimers();
    }
  });
});
