/**
 * regenerationForcing — enforces the spec §3.2.1 "system obligation".
 *
 * Independent of the goal tree, every zone observed as Barren / Compacted
 * MUST receive a regeneration pathway, and that zone MUST NOT receive
 * crops / animals / active infrastructure until the pathway is
 * acknowledged. This module is the deterministic core of that rule; it is
 * woven into `runAutoDesign` so the greedy goal-driven selection can
 * never skip a degraded zone.
 *
 * Spec ref: OLOS_Atlas_Platform_Workflow_Spec_v1.docx §3.2.1.
 */

import { phase as phaseTokens } from '../../../../lib/tokens.js';
import type { BuildPhase, PhaseTask } from '../../../../store/phaseStore.js';
import { CATALOG_VERSION } from '../../data/goalCompassTypes.js';
import type { SoilCompaction } from '../../data/goalCompassTypes.js';
import {
  buildRegenerationPathway,
  type RegenerationPathway,
} from '../../data/regenerationPathway.js';
import { resolveSpecCategory } from '../specTaxonomy.js';
import type { AllocatorZone } from './types.js';

export interface ForcedRegenerationZone {
  zoneId: string;
  pathway: RegenerationPathway;
}

export interface RegenerationForcingResult {
  /** Barren/compacted zone ids — withheld from normal allocation. */
  barrenZoneIds: string[];
  /** Per-zone mandatory pathways (surfaced in plan + report). */
  forcedZones: ForcedRegenerationZone[];
  /** Synthetic build phase carrying the regeneration tasks. */
  generatedPhase: BuildPhase | null;
  /** Regeneration tasks ready for scheduleTasksToCalendar. */
  generatedTasks: { phaseId: string; task: PhaseTask }[];
}

function detectBarrenZones(zones: AllocatorZone[]): AllocatorZone[] {
  return zones.filter(
    (z) =>
      resolveSpecCategory({
        category: z.category,
        successionStage: z.successionStage ?? null,
        groundCover: z.groundCover ?? null,
      }) === 'barren_compacted',
  );
}

/**
 * Build the forced regeneration plan for a project's barren zones.
 *
 * @param zones                       all allocator zones for the project
 * @param compaction                  site-profile soil compaction signal
 * @param acknowledgedRegenerationZoneIds zones the steward has explicitly
 *        acknowledged for regeneration — these stay barren-flagged (the
 *        pathway is still emitted) but the assignment gate is released so
 *        productive interventions may also be placed there.
 */
export function computeRegenerationForcing(
  projectId: string,
  zones: AllocatorZone[],
  compaction: SoilCompaction | null,
  acknowledgedRegenerationZoneIds: string[] = [],
): RegenerationForcingResult {
  const barren = detectBarrenZones(zones);
  if (barren.length === 0) {
    return {
      barrenZoneIds: [],
      forcedZones: [],
      generatedPhase: null,
      generatedTasks: [],
    };
  }

  const acked = new Set(acknowledgedRegenerationZoneIds);
  const barrenZoneIds = barren.map((z) => z.id);

  const generatedPhase: BuildPhase = {
    id: `regen-phase-${projectId}`,
    projectId,
    name: 'Land regeneration (mandatory)',
    timeframe: 'Year 0-4',
    order: 1,
    description:
      'Mandatory regeneration of Barren / Compacted zones. Generated by ' +
      'the regeneration obligation, independent of project goals.',
    color: phaseTokens[1],
    completed: false,
    notes: '',
    completedAt: null,
    yeomansCap: 'soil',
    generatedFromGoalCompass: true,
    catalogVersion: CATALOG_VERSION,
  };

  const forcedZones: ForcedRegenerationZone[] = [];
  const generatedTasks: { phaseId: string; task: PhaseTask }[] = [];

  for (const zone of barren) {
    const pathway = buildRegenerationPathway(compaction);
    forcedZones.push({ zoneId: zone.id, pathway });

    for (const method of pathway.methods) {
      generatedTasks.push({
        phaseId: generatedPhase.id,
        task: {
          id: `regen-task-${zone.id}-${method.id}`,
          season: method.season,
          title: `${method.name} — zone ${zone.id}`,
          laborHrs: 8,
          costUSD: 0,
          notes: method.description,
          designLayer: 'vegetation',
          generatedFromIntervention: method.interventionId ?? method.id,
          catalogVersion: CATALOG_VERSION,
          status: 'generated',
        },
      });
    }
  }

  // Gate: only zones the steward has NOT acknowledged stay withheld from
  // normal (productive) allocation. Acknowledged zones still get the
  // pathway but are allowed to also carry productive interventions.
  const gatedZoneIds = barrenZoneIds.filter((id) => !acked.has(id));

  return {
    barrenZoneIds: gatedZoneIds,
    forcedZones,
    generatedPhase,
    generatedTasks,
  };
}

/**
 * Assignment gate — remove withheld barren zones from the candidate set
 * an intervention's allocator may land in. Regeneration tasks themselves
 * are scheduled directly (not via the allocator), so this only blocks
 * productive interventions from degraded ground.
 */
export function applyAssignmentGate(
  zones: AllocatorZone[],
  withheldZoneIds: string[],
): AllocatorZone[] {
  if (withheldZoneIds.length === 0) return zones;
  const blocked = new Set(withheldZoneIds);
  return zones.filter((z) => !blocked.has(z.id));
}
