/**
 * captureSampleSeed — dev tool that snapshots ONE authored project into a
 * deterministic, covenant-clean "sample seed" JSON, ready to promote to the
 * app's built-in sample (replacing the retired 351 House / Moontrance / Three
 * Streams / Apricot Lane builtins).
 *
 * Why this exists: the clean-slate work (FLAGS.SEED_SAMPLES off + migration
 * 056) leaves "My Projects" empty. The replacement sample is authored by the
 * user IN-APP, not generated by code. This tool is the bridge: the user builds
 * the project through the normal Vision → Observe → Plan → Act flow, then runs
 * this to capture the finished result. The captured JSON is transcribed to
 * `content/authoredSampleSeed.ts` and replayed by `seedAuthoredSample.ts`
 * (client) + migration `057_builtin_authored_sample.sql` (server).
 *
 * ── How capture stays COMPLETE ────────────────────────────────────────────
 * The snapshot walks `SYNCED_STORES` — the same ~120-descriptor manifest the
 * multi-device sync uses, guarded by a build-time coverage test so no
 * project-scoped store can be silently omitted. For each descriptor we call the
 * exact getter sync itself uses:
 *   • typed-record stores → `selectRecordsForProject(state, pid)`  (per-row)
 *   • versioned-blob stores → `selectForProject(state, pid)`       (project slice)
 * Both read the live store via the descriptor's `store` handle. The 6
 * typed-design / typed-table stores (zones, built-environment-v2, paths,
 * utilities, vegetation, act-succession) intentionally carry NO generic getter
 * (they ride the `design_features` typed path), so we read them directly via
 * TYPED_STORE_READERS. A guard throws if a future manifest entry has neither a
 * getter nor a direct reader — capture fails loud rather than silently partial.
 *
 * The `ogden-projects` store is the one deliberate skip: its `selectForProject`
 * is `whole` (the ENTIRE projects list), so instead we capture the single
 * `LocalProject` row for `pid` as `projectRow` (re-seeded by an insert, never a
 * whole-store replace that would clobber the user's other projects).
 *
 * ── Determinism ───────────────────────────────────────────────────────────
 * `deepNormalize` rewrites the snapshot so re-capturing an identical project
 * yields byte-identical output regardless of when/where it ran:
 *   • every string equal to the source projectId → SAMPLE_SEED_PROJECT_ID
 *     (this also rewrites `projectRow.id` and every nested `projectId`)
 *   • object KEYS equal to the source projectId → SAMPLE_SEED_PROJECT_ID
 *     (defensive — for any pid-keyed map that survives a getter)
 *   • timestamp-named fields → the fixed epoch (date-only vs ISO preserved)
 *   • serverId / isBuiltin / activeProjectId → stripped everywhere
 *
 * ── Amanah gate (covenant-by-construction) ────────────────────────────────
 *   1. Coherence seal: the promoted sample must have passed the Coherence
 *      threshold — asserted on the RAW `ogden-coherence-check` slice BEFORE the
 *      timestamp rewrite (which would otherwise mask a missing `sealedAt`).
 *      Override with { allowUnsealed: true } (not recommended for a shipped
 *      sample).
 *   2. No advance-sale framing: every string in the FINAL snapshot is run
 *      through `detectCsaLikeText`; any hit throws (bay' ma laysa 'indak — the
 *      sale of what one does not yet possess). No override — this is the bright
 *      line. The error names the offending path + text so a false positive is
 *      diagnosable.
 *
 * ── Usage ─────────────────────────────────────────────────────────────────
 *   await window.__ogdenCaptureSampleSeed()          // active project → downloads JSON
 *   await window.__ogdenCaptureSampleSeed(projectId) // explicit project → downloads JSON
 *   window.__ogdenCaptureSampleSeedData(projectId)   // returns the object, no download
 * The project MUST be the active/open one (the active-singleton stores —
 * financial, siting-weights — capture the active project only).
 */

import { SAMPLE_SEED_PROJECT_ID } from '@ogden/shared';
import { SYNCED_STORES } from '../lib/syncManifest.js';
import { useProjectStore, type LocalProject } from '../store/projectStore.js';
import { detectCsaLikeText } from '../v3/plan/threshold/realityCheckModel.js';

// The 6 typed-design / typed-table stores that carry no generic manifest
// getter — read directly. Each is a flat array whose elements carry `projectId`.
import { useZoneStore } from '../store/zoneStore.js';
import { useBuiltEnvironmentStoreV2 } from '../store/builtEnvironmentStoreV2.js';
import { usePathStore } from '../store/pathStore.js';
import { useUtilityStore } from '../store/utilityStore.js';
import { useVegetationStore } from '../store/vegetationStore.js';
import { useSuccessionStore } from '../store/successionStore.js';

// ── Determinism constants ───────────────────────────────────────────────────

/** Fixed capture epoch — every timestamp collapses to this (mirrors the seed
 *  fixtures' `2026-06-20T00:00:00.000Z`) so re-capture is byte-stable. */
const FIXED_EPOCH = '2026-06-20T00:00:00.000Z';
const FIXED_EPOCH_DATE = '2026-06-20';
const FIXED_EPOCH_MS = new Date(FIXED_EPOCH).getTime();

/** Keys deleted wherever they appear — device/server-scoped, must never seed. */
const STRIP_KEYS = new Set(['serverId', 'isBuiltin', 'activeProjectId']);

// ── Direct readers for the 6 typed stores (no manifest getter) ──────────────

interface TypedReader {
  storeKey: string;
  /** The store state field the records live under (needed to re-seed). */
  field: string;
  read: (pid: string) => unknown[];
}

const TYPED_STORE_READERS: TypedReader[] = [
  {
    storeKey: 'ogden-zones',
    field: 'zones',
    read: (pid) => useZoneStore.getState().zones.filter((z) => z.projectId === pid),
  },
  {
    storeKey: 'ogden-built-environment-v2',
    field: 'entities',
    read: (pid) =>
      useBuiltEnvironmentStoreV2.getState().entities.filter((e) => e.projectId === pid),
  },
  {
    storeKey: 'ogden-paths',
    field: 'paths',
    read: (pid) => usePathStore.getState().paths.filter((p) => p.projectId === pid),
  },
  {
    storeKey: 'ogden-utilities',
    field: 'utilities',
    read: (pid) => useUtilityStore.getState().utilities.filter((u) => u.projectId === pid),
  },
  {
    storeKey: 'ogden-vegetation',
    field: 'patches',
    read: (pid) => useVegetationStore.getState().patches.filter((p) => p.projectId === pid),
  },
  {
    storeKey: 'ogden-act-succession',
    field: 'milestones',
    read: (pid) => useSuccessionStore.getState().milestones.filter((m) => m.projectId === pid),
  },
];

const TYPED_READER_KEYS = new Set(TYPED_STORE_READERS.map((t) => t.storeKey));

// ── Snapshot shape ──────────────────────────────────────────────────────────

/** One captured store's payload, tagged by how it must be re-applied on seed. */
export type CapturedStore =
  /** versioned-blob: re-seed via the descriptor's `applyForProject(store, pid, slice)`. */
  | { kind: 'blob'; slice: unknown }
  /** typed-record: re-seed each via `applyRecordForProject(store, pid, recordId, record)`. */
  | { kind: 'records'; records: Array<{ recordId: string; record: unknown }> }
  /** typed-design/table: re-seed by writing `setState({ [field]: [...others, ...records] })`. */
  | { kind: 'typed'; field: string; records: unknown[] };

export interface SampleSeedSnapshot {
  schema: 'ogden-sample-seed';
  version: 1;
  /** Fixed epoch (see FIXED_EPOCH) — never wall-clock, so capture is stable. */
  seededAt: string;
  /** Provenance only — the original runtime projectId. The seeder ignores it. */
  capturedFrom: string;
  /** The single project row, id rewritten to SAMPLE_SEED_PROJECT_ID, cleaned. */
  projectRow: LocalProject;
  /** Convenience hoist of `projectRow.parcelBoundaryGeojson` for migration 057. */
  boundary: GeoJSON.FeatureCollection | null;
  /** Per-store captured payloads, keyed by manifest storeKey. */
  stores: Record<string, CapturedStore>;
}

export interface CaptureOptions {
  /** Skip the Coherence-seal precondition (NOT recommended for a shipped sample). */
  allowUnsealed?: boolean;
}

// ── Determinism helpers ─────────────────────────────────────────────────────

function isTimeKey(key: string): boolean {
  return (
    /(At|Time|Timestamp|Date)$/.test(key) ||
    /_at$/.test(key) ||
    key === 'timestamp' ||
    key === 'date' ||
    key === 'time'
  );
}

/** Collapse a timestamp value to the fixed epoch, preserving its original
 *  format (date-only, ISO datetime, ms, or seconds). Non-date values pass
 *  through untouched so a mis-named field isn't corrupted. */
function normalizeTimeValue(v: unknown): unknown {
  if (typeof v === 'number') {
    if (v > 1e12) return FIXED_EPOCH_MS; // epoch millis
    if (v > 1e9) return Math.floor(FIXED_EPOCH_MS / 1000); // epoch seconds
    return v; // small number — not an epoch, leave it
  }
  if (typeof v === 'string') {
    if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return FIXED_EPOCH_DATE; // date-only
    if (/^\d{4}-\d{2}-\d{2}T/.test(v)) return FIXED_EPOCH; // ISO datetime
    return v; // non-date string under a time-ish key — leave it
  }
  return v;
}

/**
 * Recursively rewrite `value` for determinism: source pid → sentinel (strings
 * AND object keys), timestamp fields → fixed epoch, strip device/server keys.
 * Input is always JSON-safe (manifest slices + LocalProject are serialisable).
 */
function deepNormalize(value: unknown, sourcePid: string): unknown {
  if (value == null) return value;
  if (typeof value === 'string') {
    return value === sourcePid ? SAMPLE_SEED_PROJECT_ID : value;
  }
  if (typeof value !== 'object') return value; // number, boolean
  if (Array.isArray(value)) {
    return value.map((v) => deepNormalize(v, sourcePid));
  }
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    if (STRIP_KEYS.has(k)) continue;
    const key = k === sourcePid ? SAMPLE_SEED_PROJECT_ID : k;
    out[key] = isTimeKey(k) ? normalizeTimeValue(v) : deepNormalize(v, sourcePid);
  }
  return out;
}

/** True for a project slice that holds nothing for this project — pruned so the
 *  snapshot only carries stores the sample actually touched. */
function isEmptySlice(slice: unknown): boolean {
  if (slice == null) return true;
  if (Array.isArray(slice)) return slice.length === 0;
  if (typeof slice === 'object') {
    const vals = Object.values(slice as Record<string, unknown>);
    if (vals.length === 0) return true;
    return vals.every(
      (v) =>
        v == null ||
        (Array.isArray(v) && v.length === 0) ||
        (typeof v === 'object' && Object.keys(v as object).length === 0),
    );
  }
  return false;
}

// ── Amanah gate ─────────────────────────────────────────────────────────────

/** Precondition: the sample must have passed the Coherence threshold. Checked
 *  on the RAW slice (pre-normalize) so a missing seal isn't masked by the epoch
 *  rewrite. */
function assertCoherenceSealed(
  raw: Record<string, CapturedStore>,
  allowUnsealed: boolean,
): void {
  if (allowUnsealed) return;
  const cap = raw['ogden-coherence-check'];
  const slice = cap && cap.kind === 'blob' ? (cap.slice as { sealedAt?: unknown }) : null;
  if (!slice?.sealedAt) {
    throw new Error(
      '[captureSampleSeed] Coherence Check is not sealed for this project ' +
        '(ogden-coherence-check.sealedAt missing). A promoted sample must have passed the ' +
        'Coherence threshold. Seal it in Plan, then re-capture — or pass { allowUnsealed: true } ' +
        'to override (not recommended for a shipped sample).',
    );
  }
}

/** Bright-line covenant check: no advance-sale / subscription / CSA framing
 *  anywhere in the promoted sample (bay' ma laysa 'indak). No override. */
function assertCovenantClean(snapshot: SampleSeedSnapshot): void {
  const hits: string[] = [];
  const walk = (v: unknown, path: string): void => {
    if (typeof v === 'string') {
      if (detectCsaLikeText(v)) hits.push(`${path}: "${v.slice(0, 120)}"`);
      return;
    }
    if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, `${path}[${i}]`));
      return;
    }
    if (v && typeof v === 'object') {
      for (const [k, val] of Object.entries(v)) walk(val, path ? `${path}.${k}` : k);
    }
  };
  walk(snapshot.projectRow, 'projectRow');
  walk(snapshot.stores, 'stores');
  if (hits.length) {
    throw new Error(
      "[captureSampleSeed] Amanah gate: advance-sale / subscription / CSA framing detected — " +
        "the sample cannot be promoted with this wording (bay' ma laysa 'indak, the sale of what " +
        'one does not yet possess). Offending text:\n  ' +
        hits.join('\n  '),
    );
  }
}

// ── Capture ─────────────────────────────────────────────────────────────────

/**
 * Capture one project into a deterministic, covenant-clean SampleSeedSnapshot.
 * `projectId` defaults to the active project. Throws if the project isn't
 * active (the active-singleton stores capture the active project only), if the
 * Coherence check isn't sealed, or if any CSA-like text is present.
 */
export function captureSampleSeed(
  projectId?: string,
  opts: CaptureOptions = {},
): SampleSeedSnapshot {
  const ps = useProjectStore.getState();
  const pid = projectId ?? ps.activeProjectId ?? undefined;
  if (!pid) {
    throw new Error('[captureSampleSeed] no projectId given and no active project.');
  }
  const source = ps.projects.find((p) => p.id === pid);
  if (!source) {
    throw new Error(`[captureSampleSeed] no project "${pid}" in the projects store.`);
  }
  if (ps.activeProjectId !== pid) {
    throw new Error(
      `[captureSampleSeed] open/activate the project first (active=${ps.activeProjectId ?? 'none'}). ` +
        'The active-singleton stores (financial, siting-weights) capture the ACTIVE project only.',
    );
  }

  // 1. Walk the manifest. `ogden-projects` is captured as `projectRow` below.
  const rawStores: Record<string, CapturedStore> = {};
  for (const d of SYNCED_STORES) {
    if (d.storeKey === 'ogden-projects') continue;
    try {
      if (d.selectRecordsForProject && d.store) {
        const records = d
          .selectRecordsForProject(d.store.getState(), pid)
          .map(({ recordId, record }) => ({ recordId, record }));
        if (records.length) rawStores[d.storeKey] = { kind: 'records', records };
      } else if (d.selectForProject && d.store) {
        const slice = d.selectForProject(d.store.getState(), pid);
        if (!isEmptySlice(slice)) rawStores[d.storeKey] = { kind: 'blob', slice };
      } else if (!TYPED_READER_KEYS.has(d.storeKey)) {
        throw new Error(
          `store "${d.storeKey}" has no manifest getter and no direct reader — ` +
            'add it to TYPED_STORE_READERS.',
        );
      }
    } catch (err) {
      throw new Error(`[captureSampleSeed] failed reading "${d.storeKey}": ${String(err)}`);
    }
  }

  // 2. The 6 typed stores (no manifest getter) — read directly.
  for (const t of TYPED_STORE_READERS) {
    const records = t.read(pid);
    if (records.length) {
      rawStores[t.storeKey] = { kind: 'typed', field: t.field, records };
    }
  }

  // 3. Amanah precondition on RAW slices (before determinism can mask a seal).
  assertCoherenceSealed(rawStores, opts.allowUnsealed ?? false);

  // 4. Determinism rewrite (source pid → sentinel; also rewrites projectRow.id
  //    and strips serverId/isBuiltin, so no separate row-cleaning step needed).
  const projectRow = deepNormalize(source, pid) as LocalProject;
  const stores: Record<string, CapturedStore> = {};
  for (const [key, cap] of Object.entries(rawStores)) {
    stores[key] = deepNormalize(cap, pid) as CapturedStore;
  }

  const assembled: SampleSeedSnapshot = {
    schema: 'ogden-sample-seed',
    version: 1,
    seededAt: FIXED_EPOCH,
    capturedFrom: pid,
    projectRow,
    boundary: projectRow.parcelBoundaryGeojson ?? null,
    stores,
  };

  // 5. Sanitise to the wire form so the returned object is byte-identical to the
  //    downloaded JSON. The active-singleton `whole` stores (financial,
  //    siting-weights) select the ENTIRE live state, which carries Zustand action
  //    functions; JSON drops them exactly as `downloadSampleSeed` does, so the
  //    in-memory snapshot, the shipped artifact, and the plan's byte-identical
  //    re-projection check all agree. Manifest slices are otherwise JSON-safe by
  //    contract, so this is a no-op for every other store.
  const snapshot = JSON.parse(JSON.stringify(assembled)) as SampleSeedSnapshot;

  // 6. Amanah bright line on the FINAL (wire) snapshot.
  assertCovenantClean(snapshot);

  return snapshot;
}

// ── Download + dev hooks ────────────────────────────────────────────────────

/** Mirror of ProjectBundleBar.triggerDownload — Blob → anchor → click → revoke. */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Capture + download the snapshot JSON (the primary promote-to-seed action). */
export function downloadSampleSeed(
  projectId?: string,
  opts: CaptureOptions = {},
): SampleSeedSnapshot {
  const snapshot = captureSampleSeed(projectId, opts);
  const json = JSON.stringify(snapshot, null, 2);
  triggerDownload(
    new Blob([json], { type: 'application/json;charset=utf-8' }),
    'ogden-sample-seed.json',
  );
  console.info('[captureSampleSeed] captured sample seed', {
    from: snapshot.capturedFrom,
    stores: Object.keys(snapshot.stores).length,
    bytes: json.length,
  });
  return snapshot;
}

// Dev hooks — mirror the other window.__ogden* dev tools (seeders, reset).
if (typeof window !== 'undefined') {
  const w = window as unknown as Record<string, unknown>;
  // Capture AND download the JSON.
  w.__ogdenCaptureSampleSeed = (projectId?: string, opts?: CaptureOptions) =>
    downloadSampleSeed(projectId, opts);
  // Return the snapshot object without downloading (console / test use).
  w.__ogdenCaptureSampleSeedData = (projectId?: string, opts?: CaptureOptions) =>
    captureSampleSeed(projectId, opts);
}
