// Centralised Lucide icon registry for atlas-ui.
// Mirrors the MILOS pattern (src/data/icon-registry.js): one import surface,
// stable camelCase keys decoupled from Lucide export names so renames/upgrades
// don't ripple through call sites.
//
// Usage:
//   import { Icon } from "../icons.js";
//   <Icon.search />
//   <Icon.alertTriangle aria-hidden="true" />

import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Beaker,
  Bell,
  Binoculars,
  BookOpen,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  ClipboardList,
  Clock,
  Clock3,
  CloudLightning,
  Compass,
  Download,
  Droplet,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  Gauge,
  Grid2X2,
  Hammer,
  Heart,
  Home,
  Info,
  Layers,
  Layers3,
  Leaf,
  Lightbulb,
  Mail,
  Map,
  MapPin,
  Maximize2,
  MoreVertical,
  Mountain,
  Network,
  PenLine,
  Plus,
  RotateCcw,
  Ruler,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Snowflake,
  Sprout,
  Star,
  Sun,
  Target,
  Timer,
  Trees,
  Triangle,
  TriangleAlert,
  UserRound,
  Users,
  Waves,
  Wind,
  X,
} from "lucide-react";

export const Icon = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  barChart: BarChart3,
  beaker: Beaker,
  bell: Bell,
  binoculars: Binoculars,
  bookOpen: BookOpen,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  circleCheck: CircleCheck,
  circleDot: CircleDot,
  circleHelp: CircleHelp,
  clipboard: ClipboardList,
  clock: Clock,
  clock3: Clock3,
  cloudLightning: CloudLightning,
  compass: Compass,
  download: Download,
  droplet: Droplet,
  edit: Edit3,
  externalLink: ExternalLink,
  eye: Eye,
  fileText: FileText,
  filter: Filter,
  flag: Flag,
  flask: FlaskConical,
  gauge: Gauge,
  grid: Grid2X2,
  hammer: Hammer,
  heart: Heart,
  home: Home,
  info: Info,
  layers: Layers,
  layers3: Layers3,
  leaf: Leaf,
  lightbulb: Lightbulb,
  mail: Mail,
  map: Map,
  mapPin: MapPin,
  maximize: Maximize2,
  moreVertical: MoreVertical,
  mountain: Mountain,
  network: Network,
  penLine: PenLine,
  plus: Plus,
  rotateCcw: RotateCcw,
  ruler: Ruler,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  sliders: SlidersHorizontal,
  snowflake: Snowflake,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  target: Target,
  timer: Timer,
  trees: Trees,
  triangle: Triangle,
  triangleAlert: TriangleAlert,
  user: UserRound,
  users: Users,
  waves: Waves,
  wind: Wind,
  x: X,
};
