// apps/web/src/lib/evidence/selectors/siteNarrative.ts
//
// Phase E.2 — SiteSummaryNarrativeSection evidence selector.
//
// The narrative card already renders an AI-generated synthesis;
// Evidence exposes the model version, the input scalars that fed the
// prompt, and the enrichment state (so a viewer can tell whether the
// narrative was actually generated vs. fallback boilerplate).

import type { EvidenceItem, EvidenceFragment } from '../types.js';

export interface SiteNarrativeEvidenceInputs {
  acreage: number | null;
  layerCount: number;
  liveCount?: number;
  /** From AIEnrichmentState in siteDataStore. */
  modelVersion?: string;
  /** True when `aiNarrative` is populated (not fallback prose). */
  hasAiNarrative: boolean;
  /** Optional caveat line (e.g., low layer-count warning). */
  caveat?: string;
}

export function selectSiteNarrativeEvidence(
  inputs: SiteNarrativeEvidenceInputs,
): EvidenceItem {
  const { acreage, layerCount, liveCount, modelVersion, hasAiNarrative, caveat } =
    inputs;

  const evidence: EvidenceFragment[] = [
    {
      label: 'Property size',
      value: acreage ?? 0,
      unit: 'acres',
      source: {
        kind: 'fixture',
        derivation: 'project.acreage',
        confidence: 'high',
      },
    },
    {
      label: 'Layer count',
      value: layerCount,
      source: {
        kind: 'computed',
        derivation: 'projectLayerRoster',
        confidence: layerCount >= 5 ? 'high' : 'medium',
      },
    },
    {
      label: 'Narrative state',
      value: hasAiNarrative ? 'AI-generated' : 'fallback',
      source: {
        kind: 'computed',
        derivation: 'AIEnrichmentState.aiNarrative',
        confidence: hasAiNarrative ? 'medium' : 'low',
      },
      methodologyHint: hasAiNarrative
        ? 'Generated by ClaudeClient against the layer summary roster.'
        : 'Pattern-based prose; AI enrichment not yet run.',
    },
  ];

  if (typeof liveCount === 'number') {
    evidence.push({
      label: 'Live (non-stale) layers',
      value: liveCount,
      source: {
        kind: 'computed',
        derivation: 'liveLayerCount',
        confidence: 'high',
      },
    });
  }

  if (modelVersion) {
    evidence.push({
      label: 'AI model',
      value: modelVersion,
      source: {
        kind: 'computed',
        derivation: 'AIEnrichmentState.modelVersion',
        confidence: 'high',
      },
    });
  }

  if (caveat) {
    evidence.push({
      label: 'Caveat',
      value: caveat,
      source: {
        kind: 'computed',
        derivation: 'narrativeCaveat',
        confidence: 'low',
      },
    });
  }

  return {
    panelKey: 'site-narrative',
    summary: {
      label: 'Narrative',
      value: hasAiNarrative ? 'AI-generated' : 'fallback prose',
    },
    evidence,
  };
}
