/**
 * elementHeights — per-kind 3D model registry for Plan-stage design
 * elements. Read by two renderers:
 *
 *  - `DesignElementScenegraphLayer` consumes entries with `mode: 'glb'` and
 *    loads `glbUrl` via deck.gl `ScenegraphLayer` (replaces the retired
 *    three.js `DesignElementGlbLayer` per ADR 2026-05-11).
 *  - `DesignElementExtrusionLayer` consumes entries with `mode: 'extrusion'`
 *    and drives MapLibre `fill-extrusion-height` / `fill-extrusion-base`.
 *    It also acts as a fallback for kinds whose GLB fails to load — the
 *    layer remains mounted but skips kinds explicitly switched to GLB.
 *
 * Lines (paths, swales, roads) and intentionally-flat polygons (paddocks,
 * orchards, silvopasture, pasture-mix, turnaround) are excluded from this
 * registry; they keep their flat fills in `DesignElementLayers`.
 *
 * As of Phase 2 (2026-05-11, ADR `2026-05-11-atlas-deckgl-scenegraph-migration`)
 * every entry points at a per-kind procedural GLB authored by
 * `scripts/gen-structure-glbs.mjs` (and the shared writer/primitives in
 * `scripts/lib/`). Output lives at `public/models/structures/<kind>.glb`.
 * `_generic_box.glb` is retained as the catch-all fallback for kinds added
 * to the registry before their own authored mesh ships.
 */

import type { DesignCategory } from './elementCatalog.js';

export type ElementModelMode = 'extrusion' | 'glb';

/** Catch-all fallback path. Generated by `scripts/gen-generic-box-glb.mjs`. */
export const GENERIC_BOX_GLB_URL = '/models/structures/_generic_box.glb';
const MODEL = (kind: string) => `/models/structures/${kind}.glb`;
const VEG_MODEL = (kind: string) => `/models/vegetation/${kind}.glb`;
const EARTH_MODEL = (kind: string) => `/models/earthworks/${kind}.glb`;

export interface ElementHeightSpec {
  /** Renderer to use for this kind. */
  mode: ElementModelMode;

  // ── Common (used by both renderers) ────────────────────────────────────
  /** Nominal real-world height in metres. For polygons, GLB scales Y to this;
   *  for points, also the visual top of the box. */
  heightM: number;
  /** Base of the model in metres above ground. Negative for sunk features
   *  (ponds). Both renderers respect this. */
  baseM?: number;
  /** Side length of the inflated square for point geometries (metres).
   *  Ignored for polygon-geometry kinds. */
  footprintM: number;
  /** Optional colour override; falls back to elementCatalog colour. Used by
   *  the extrusion fallback path; ignored by the GLB renderer (which uses
   *  the model's authored materials). */
  color?: string;

  // ── GLB-only ───────────────────────────────────────────────────────────
  /** Absolute URL to the GLB. Only read when `mode === 'glb'`. */
  glbUrl?: string;
  /** Optional default rotation around the vertical (Y) axis, degrees.
   *  Useful for kinds with a "front" (e.g. machinery sheds). */
  glbRotationDeg?: number;
  /** Optional anchor offset applied after scaling, in local metres
   *  `[x, y, z]`. Use to nudge models whose pivot is not at the base
   *  centre. The fallback box is authored anchored at base-centre so
   *  the default `undefined` is correct. */
  glbAnchorOffsetM?: [number, number, number];

  /** Bookkeeping only — not used by the renderers. */
  category?: DesignCategory;
}

/**
 * Kind → spec. Only kinds in this map participate in 3D rendering.
 *
 * Heights are conservative — small enough that a barn does not look like a
 * skyscraper at typical zooms (z14–z18), large enough to read as 3D when
 * the user pitches the camera.
 */
export const ELEMENT_HEIGHTS: Record<string, ElementHeightSpec> = {
  // ── Buildings (polygon) ───────────────────────────────────────────────
  // No bespoke GLB — buildings are user-drawn polygons (BuildingTool) or
  // adopted basemap footprints (AdoptBasemapBuildingTool). Extrudes the
  // polygon at `proposed.heightM` if the entity has it (DesignElementExtrusionLayer
  // prefers entity height when present); otherwise falls back to a
  // conservative single-storey default.
  building:         { mode: 'extrusion',                              heightM: 6.0, footprintM: 0,  category: 'structure' },

  // ── Structures (point) ────────────────────────────────────────────────
  yurt:             { mode: 'glb', glbUrl: MODEL('yurt'),             heightM: 3.5, footprintM: 6,  category: 'structure' },
  greenhouse:       { mode: 'glb', glbUrl: MODEL('greenhouse'),       heightM: 3.0, footprintM: 8,  category: 'structure' },
  barn:             { mode: 'glb', glbUrl: MODEL('barn'),             heightM: 6.0, footprintM: 10, category: 'structure' },
  shed:             { mode: 'glb', glbUrl: MODEL('shed'),             heightM: 2.5, footprintM: 4,  category: 'structure' },

  // ── Machinery (point + polygon) ──────────────────────────────────────
  'machinery-shed': { mode: 'glb', glbUrl: MODEL('machinery-shed'),   heightM: 4.0, footprintM: 8,  category: 'machinery' },
  'fuel-station':   { mode: 'glb', glbUrl: MODEL('fuel-station'),     heightM: 3.5, footprintM: 6,  category: 'machinery' },
  'equipment-yard': { mode: 'glb', glbUrl: MODEL('equipment-yard'),   heightM: 0.3, footprintM: 0,  category: 'machinery' },

  // ── Water (point + polygon) ──────────────────────────────────────────
  'water-tank':     { mode: 'glb', glbUrl: MODEL('water-tank'),       heightM: 4.0, footprintM: 4,  category: 'water' },
  // Pond: sunk below ground. The pond GLB is a thin disc; baseM negative
  // sinks the rim below grade so the water surface reads as a depression
  // at typical Plan/Observe pitch.
  pond:             { mode: 'glb', glbUrl: MODEL('pond'),             heightM: 0.1, baseM: -0.8, footprintM: 6, category: 'water' },
  spring:           { mode: 'glb', glbUrl: MODEL('spring'),           heightM: 0.6, footprintM: 2,  category: 'water' },

  // ── Amenity (point + polygon) ────────────────────────────────────────
  'prayer-pavilion':{ mode: 'glb', glbUrl: MODEL('prayer-pavilion'),  heightM: 5.0, footprintM: 7,  category: 'amenity' },
  parking:          { mode: 'glb', glbUrl: MODEL('parking'),          heightM: 0.2, footprintM: 6,  category: 'amenity' },
  'fire-circle':    { mode: 'glb', glbUrl: MODEL('fire-circle'),      heightM: 0.4, footprintM: 2,  category: 'amenity' },
  compost:          { mode: 'glb', glbUrl: MODEL('compost'),          heightM: 1.0, footprintM: 2,  category: 'amenity' },

  // ── Vegetation (point) — Phase 3 of ADR 2026-05-11. Hedgerow is line
  // geometry and renders flat in BeV2GenericLayer; excluded from 3D.
  'oak-tree':       { mode: 'glb', glbUrl: VEG_MODEL('oak-tree'),     heightM: 12,  footprintM: 8,  category: 'vegetation' },
  'pine-tree':      { mode: 'glb', glbUrl: VEG_MODEL('pine-tree'),    heightM: 15,  footprintM: 5,  category: 'vegetation' },
  'apple-tree':     { mode: 'glb', glbUrl: VEG_MODEL('apple-tree'),   heightM: 5,   footprintM: 5,  category: 'vegetation' },
  shrub:            { mode: 'glb', glbUrl: VEG_MODEL('shrub'),        heightM: 1.5, footprintM: 2,  category: 'vegetation' },

  // ── Earthworks (point) — Phase 4 of ADR 2026-05-11. ───────────────────
  berm:             { mode: 'glb', glbUrl: EARTH_MODEL('berm'),       heightM: 1.5, footprintM: 8,  category: 'earthworks' },
  'raised-bed':     { mode: 'glb', glbUrl: EARTH_MODEL('raised-bed'), heightM: 0.6, footprintM: 2,  category: 'earthworks' },
  terrace:          { mode: 'glb', glbUrl: EARTH_MODEL('terrace'),    heightM: 1.2, footprintM: 10, category: 'earthworks' },

  // ── Custom GLB upload (Phase 6 of ADR 2026-05-11) ─────────────────────
  // Spec is a placeholder — the scenegraph layer overrides `glbUrl` with the
  // blob URL resolved from `customModelStore.entries[proposed.customModelId]`.
  // `_generic_box.glb` is used if the customModelId cannot be resolved.
  'custom-glb':     { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL,         heightM: 3,   footprintM: 3,   category: 'amenity' },
};

export function getElementHeightSpec(kind: string): ElementHeightSpec | undefined {
  return ELEMENT_HEIGHTS[kind];
}

export const EXTRUDED_KINDS: ReadonlySet<string> = new Set(Object.keys(ELEMENT_HEIGHTS));
