/**
 * elementHeights — per-kind 3D model registry for Plan-stage design
 * elements. Read by two renderers:
 *
 *  - `DesignElementGlbLayer` consumes entries with `mode: 'glb'` and
 *    loads `glbUrl` via three.js GLTFLoader.
 *  - `DesignElementExtrusionLayer` consumes entries with `mode: 'extrusion'`
 *    and drives MapLibre `fill-extrusion-height` / `fill-extrusion-base`.
 *    It also acts as a fallback for kinds whose GLB fails to load — the
 *    layer remains mounted but skips kinds explicitly switched to GLB.
 *
 * Lines (paths, swales, roads) and intentionally-flat polygons (paddocks,
 * orchards, silvopasture, pasture-mix, turnaround) are excluded from this
 * registry; they keep their flat fills in `DesignElementLayers`.
 *
 * As of Phase 2 (2026-05-10) every entry is `mode: 'glb'` and points at
 * the procedural fallback `/models/structures/_generic_box.glb`. Per-kind
 * authored GLBs can be dropped into `public/models/structures/<kind>.glb`
 * and wired up by updating only that kind's `glbUrl`.
 */

import type { DesignCategory } from './elementCatalog.js';

export type ElementModelMode = 'extrusion' | 'glb';

/** Default fallback path. Generated by `scripts/gen-generic-box-glb.mjs`. */
export const GENERIC_BOX_GLB_URL = '/models/structures/_generic_box.glb';

export interface ElementHeightSpec {
  /** Renderer to use for this kind. */
  mode: ElementModelMode;

  // ── Common (used by both renderers) ────────────────────────────────────
  /** Nominal real-world height in metres. For polygons, GLB scales Y to this;
   *  for points, also the visual top of the box. */
  heightM: number;
  /** Base of the model in metres above ground. Negative for sunk features
   *  (ponds). Both renderers respect this. */
  baseM?: number;
  /** Side length of the inflated square for point geometries (metres).
   *  Ignored for polygon-geometry kinds. */
  footprintM: number;
  /** Optional colour override; falls back to elementCatalog colour. Used by
   *  the extrusion fallback path; ignored by the GLB renderer (which uses
   *  the model's authored materials). */
  color?: string;

  // ── GLB-only ───────────────────────────────────────────────────────────
  /** Absolute URL to the GLB. Only read when `mode === 'glb'`. */
  glbUrl?: string;
  /** Optional default rotation around the vertical (Y) axis, degrees.
   *  Useful for kinds with a "front" (e.g. machinery sheds). */
  glbRotationDeg?: number;
  /** Optional anchor offset applied after scaling, in local metres
   *  `[x, y, z]`. Use to nudge models whose pivot is not at the base
   *  centre. The fallback box is authored anchored at base-centre so
   *  the default `undefined` is correct. */
  glbAnchorOffsetM?: [number, number, number];

  /** Bookkeeping only — not used by the renderers. */
  category?: DesignCategory;
}

/**
 * Kind → spec. Only kinds in this map participate in 3D rendering.
 *
 * Heights are conservative — small enough that a barn does not look like a
 * skyscraper at typical zooms (z14–z18), large enough to read as 3D when
 * the user pitches the camera.
 */
export const ELEMENT_HEIGHTS: Record<string, ElementHeightSpec> = {
  // ── Structures (point) ────────────────────────────────────────────────
  yurt:             { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 3.5, footprintM: 6,  category: 'structure' },
  greenhouse:       { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 3.0, footprintM: 8,  category: 'structure' },
  barn:             { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 6.0, footprintM: 10, category: 'structure' },
  shed:             { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 2.5, footprintM: 4,  category: 'structure' },

  // ── Machinery (point + polygon) ──────────────────────────────────────
  'machinery-shed': { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 4.0, footprintM: 8,  category: 'machinery' },
  'fuel-station':   { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 3.0, footprintM: 5,  category: 'machinery' },
  'equipment-yard': { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 0.3, footprintM: 0,  category: 'machinery' },

  // ── Water (point + polygon) ──────────────────────────────────────────
  'water-tank':     { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 3.0, footprintM: 4,  category: 'water' },
  // Pond: sunk below ground. baseM negative + heightM 0 yields a depression
  // when pitched in either renderer.
  pond:             { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 0,   baseM: -0.8, footprintM: 0, category: 'water' },
  spring:           { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 0.5, footprintM: 1.5, category: 'water' },

  // ── Amenity (point + polygon) ────────────────────────────────────────
  'prayer-pavilion':{ mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 4.0, footprintM: 7,  category: 'amenity' },
  parking:          { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 0.2, footprintM: 6,  category: 'amenity' },
  'fire-circle':    { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 0.4, footprintM: 2,  category: 'amenity' },
  compost:          { mode: 'glb', glbUrl: GENERIC_BOX_GLB_URL, heightM: 1.0, footprintM: 0,  category: 'amenity' },
};

export function getElementHeightSpec(kind: string): ElementHeightSpec | undefined {
  return ELEMENT_HEIGHTS[kind];
}

export const EXTRUDED_KINDS: ReadonlySet<string> = new Set(Object.keys(ELEMENT_HEIGHTS));
