/**
 * Feature manifest — single source of truth for the 30 feature sections.
 *
 * Consumed by:
 *   - UI chrome (nav, coming-soon banners, feature cards) via
 *     `isFeatureVisible()` helper.
 *   - API feature-gate plugin (`fastify.requirePhase(tag)`) to 404 routes
 *     whose section is beyond the configured `ATLAS_PHASE_MAX`.
 *
 * Phase tags follow the sectioned feature spec (see
 * `feature-sections-1-30-the-stateless-lollipop.md`):
 *   P1 — core intake / must-have for first usable build
 *   P2 — advanced imports, templates, comparison tooling
 *   P3 — collaboration, portal, external stakeholders
 *   P4 — mature AI/automation / cross-project intelligence
 *   MT — OGDEN Moontrance identity features (separate timeline)
 *
 * Section status is informational only; the source of truth for "is this
 * wired up" remains the routes + components themselves. The manifest is
 * for tagging and gating, not progress tracking.
 *
 * The 30 numbered `<slug>` folders under `apps/web/src/features/<slug>/`
 * are scaffold orphans generated by `apps/api/scripts/scaffold-section.ts`
 * and are NOT registered in the router. The canonical surface map is
 * `apps/web/src/features/navigation/taxonomy.ts` (drives DashboardSidebar
 * and IconSidebar). When the manifest's `status` and the visible UI
 * disagree, `taxonomy.ts` and the actually-mounted panels win.
 */

export type PhaseTag = 'P1' | 'P2' | 'P3' | 'P4' | 'MT' | 'FUTURE';

export type SectionStatus = 'done' | 'partial' | 'stub' | 'planned';

export interface FeatureItem {
  /** Stable key, e.g. 'import-kml'. Kebab-case. */
  key: string;
  /** Human-readable label from the feature spec. */
  label: string;
  phase: PhaseTag;
  status: SectionStatus;
}

export interface FeatureSection {
  /** 1-30 per the sectioned spec. */
  id: number;
  /** Kebab-case slug, used for route prefixes and feature-folder names. */
  slug: string;
  /** Section title from the spec. */
  name: string;
  /** Union of phase tags across this section's items. */
  phases: PhaseTag[];
  status: SectionStatus;
  features: FeatureItem[];
}

/**
 * Ordinal ranking used by `phaseAtMost()` for `ATLAS_PHASE_MAX` gating.
 * MT and FUTURE sit off the P-tag ordinal scale. Both require their own
 * flag (`ATLAS_MOONTRANCE`, `ATLAS_FUTURE`) — phaseAtMost rejects them
 * unless explicitly allowed.
 */
const PHASE_ORDER: Record<PhaseTag, number> = {
  P1: 1,
  P2: 2,
  P3: 3,
  P4: 4,
  MT: 99,
  FUTURE: 98,
};

export const FEATURE_SECTIONS: readonly FeatureSection[] = [
  {
    id: 1,
    slug: 'project-intake',
    name: 'Project Creation & Property Intake',
    phases: ['P1', 'P2'],
    status: 'done',
    features: [
      { key: 'create-project', label: 'Create new project', phase: 'P1', status: 'done' },
      { key: 'project-dashboard', label: 'Project dashboard', phase: 'P1', status: 'done' },
      { key: 'address-parcel-gps', label: 'Property address, parcel ID, GPS coordinate input', phase: 'P1', status: 'done' },
      { key: 'draw-import-boundary', label: 'Draw / import parcel boundary', phase: 'P1', status: 'done' },
      { key: 'import-kml-kmz-geojson-shp', label: 'Import KML / KMZ / GeoJSON / Shapefile data', phase: 'P1', status: 'done' },
      { key: 'upload-title-survey-siteplan', label: 'Upload title map / survey / site plan', phase: 'P1', status: 'done' },
      { key: 'import-drone-ortho-terrain', label: 'Import drone, orthomosaic, terrain model imagery', phase: 'P2', status: 'planned' },
      { key: 'assign-type-intent', label: 'Assign project type and design intent', phase: 'P1', status: 'done' },
      { key: 'owner-stakeholder-notes', label: 'Save owner / stakeholder notes', phase: 'P1', status: 'partial' },
      { key: 'attach-media', label: 'Attach photos, videos, documents, site notes', phase: 'P1', status: 'done' },
      { key: 'field-observations-legal', label: 'Add field observations and legal description', phase: 'P1', status: 'partial' },
      { key: 'zoning-utility-notes', label: 'Add zoning, municipal, access, utility notes', phase: 'P1', status: 'partial' },
      { key: 'restrictions-covenants', label: 'Add restrictions / covenants notes', phase: 'P1', status: 'partial' },
      { key: 'climate-bioregion-county', label: 'Add climate region, bioregion, county metadata', phase: 'P1', status: 'partial' },
      { key: 'units-projection', label: 'Set units and map projection', phase: 'P1', status: 'done' },
      { key: 'project-permissions', label: 'Set project permissions', phase: 'P1', status: 'done' },
      { key: 'autosave-versions', label: 'Auto-save and version snapshots', phase: 'P1', status: 'done' },
      { key: 'restore-previous', label: 'Restore previous project state', phase: 'P2', status: 'partial' },
      { key: 'save-candidates', label: 'Save multiple candidate properties', phase: 'P2', status: 'done' },
      { key: 'compare-candidates', label: 'Compare candidate properties side by side', phase: 'P2', status: 'done' },
      { key: 'duplicate-from-template', label: 'Duplicate project from template', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 2,
    slug: 'basemap-terrain',
    name: 'Base Map, Imagery & Terrain Visualization',
    phases: ['P1', 'P2'],
    status: 'done',
    features: [
      { key: 'basemap-style-switcher', label: 'Satellite, aerial, topographic, street, hybrid map views', phase: 'P1', status: 'done' },
      { key: 'terrain-contour-hillshade', label: 'Terrain mesh, contour line, elevation shading, hillshade rendering', phase: 'P1', status: 'done' },
      { key: 'slope-aspect-heatmaps', label: 'Slope and aspect heatmaps', phase: 'P1', status: 'done' },
      { key: 'map-mode-2d', label: '2D map mode', phase: 'P1', status: 'done' },
      { key: 'map-mode-2-5d-3d', label: '2.5D tilted and full 3D terrain modes', phase: 'P2', status: 'done' },
      { key: 'vector-overlays-parcel-road-water-building', label: 'Parcel boundary, road, waterbody, building footprint overlays', phase: 'P1', status: 'done' },
      { key: 'measure-distance-area-elevation', label: 'Distance, area, elevation measurement tools', phase: 'P1', status: 'done' },
      { key: 'cross-section-profile', label: 'Cross-section profile tool', phase: 'P2', status: 'done' },
      { key: 'line-of-sight-viewshed', label: 'Line-of-sight and viewshed analysis tools', phase: 'P2', status: 'done' },
      { key: 'layer-visibility-order-opacity', label: 'Layer visibility toggles, ordering, opacity controls', phase: 'P1', status: 'done' },
      { key: 'historical-imagery', label: 'Historical imagery layers', phase: 'P2', status: 'done' },
      { key: 'split-screen-compare', label: 'Split screen and before/after compare modes', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 3,
    slug: 'site-data-layers',
    name: 'Site Data Layers & Environmental Inputs',
    phases: ['P1', 'P2'],
    status: 'partial',
    features: [
      { key: 'elevation-slope-aspect-curvature', label: 'Elevation, slope, aspect, curvature data (USGS 3DEP — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'watershed-drainage-network', label: 'Watershed boundary and drainage network (NHD — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'soil-survey-ssurgo', label: 'Soil survey, texture, drainage class layers (SSURGO — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'wetland-floodplain-overlays', label: 'Wetland and floodplain overlays (NWI, FEMA — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'landcover-vegetation-nlcd', label: 'Land cover and vegetation classification (NLCD — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'climate-normals-noaa', label: 'Climate normals, precipitation, temperature, frost risk (NOAA — Tier 1)', phase: 'P1', status: 'done' },
      { key: 'drone-ortho-terrain', label: 'User-uploaded drone imagery, orthomosaic, terrain model (Tier 2)', phase: 'P2', status: 'planned' },
      { key: 'manual-soil-water-tests', label: 'Manual soil test entry, water test data (Tier 2)', phase: 'P2', status: 'planned' },
      { key: 'geological-bedrock-notes', label: 'Geological substrate, bedrock depth notes', phase: 'P2', status: 'planned' },
      { key: 'solar-wind-fire', label: 'Solar radiation, wind rose, fire risk layers', phase: 'P2', status: 'planned' },
      { key: 'habitat-wildlife-corridors', label: 'Habitat, wildlife corridor, protected species notes', phase: 'P2', status: 'planned' },
      { key: 'adjacent-landuse-utilities', label: 'Adjacent land use, infrastructure proximity, utility network notes', phase: 'P2', status: 'planned' },
      { key: 'legal-setback-easement-zoning', label: 'Legal setback, easement, municipal zoning overlays (see Section 0e)', phase: 'P1', status: 'done' },
      { key: 'data-completeness-score', label: 'Data Completeness Score on project dashboard', phase: 'P1', status: 'done' },
    ],
  },
  {
    id: 4,
    slug: 'site-assessment',
    name: 'Site Assessment & Diagnostic Atlas',
    phases: ['P1', 'P2'],
    status: 'partial',
    features: [
      { key: 'automated-site-summary', label: 'Automated site summary with data source attribution', phase: 'P1', status: 'done' },
      { key: 'suitability-regen-buildability-scores', label: 'Property suitability, regenerative potential, buildability scores (with confidence indicators)', phase: 'P1', status: 'done' },
      { key: 'water-ag-habitat-scores', label: 'Water resilience, agricultural suitability, habitat sensitivity scores', phase: 'P1', status: 'done' },
      { key: 'risk-opportunity-limitation-summaries', label: 'Risk summary, opportunity summary, limitation summary', phase: 'P1', status: 'partial' },
      { key: 'steep-slope-flood-frost-wind-detection', label: 'Steep slope, flood-prone area, frost pocket, wind exposure detection', phase: 'P1', status: 'done' },
      { key: 'sun-trap-dry-wet-erosion-compaction', label: 'Sun trap, dry/wet zone, erosion hotspot, compaction risk identification', phase: 'P2', status: 'partial' },
      { key: 'natural-shelter-solar-exposure', label: 'Natural shelter zone and solar exposure analysis', phase: 'P2', status: 'done' },
      { key: 'microclimate-cold-air-drainage', label: 'Microclimate and cold-air drainage analysis', phase: 'P2', status: 'done' },
      { key: 'candidate-zones-pond-swale-keyline-orchard-grazing-structure', label: 'Pond, swale, keyline, orchard, grazing, structure candidate zones', phase: 'P2', status: 'partial' },
      { key: 'restoration-priority-regeneration-sequence', label: 'Restoration priority map and regeneration sequence suggestion', phase: 'P2', status: 'partial' },
      { key: 'what-this-land-wants', label: "'What this land wants' summary (AI)", phase: 'P2', status: 'partial' },
      { key: 'threats-and-leverage-interventions', label: "'Main threats to success' and 'Highest leverage interventions' summaries", phase: 'P2', status: 'partial' },
    ],
  },
  {
    id: 5,
    slug: 'hydrology-water',
    name: 'Hydrology & Water Systems Planning',
    phases: ['P1', 'P2'],
    status: 'partial',
    features: [
      { key: 'water-flow-runoff-visualization', label: 'Water flow visualization, surface runoff paths', phase: 'P1', status: 'done' },
      { key: 'watershed-delineation', label: 'Watershed delineation, catchment area identification', phase: 'P1', status: 'done' },
      { key: 'drainage-line-flood-accumulation', label: 'Drainage line extraction, flood accumulation simulation', phase: 'P1', status: 'done' },
      { key: 'pond-swale-berm-check-dam-suggestions', label: 'Pond, swale, berm, check dam placement suggestions', phase: 'P2', status: 'done' },
      { key: 'overflow-spillway-planning', label: 'Overflow route visualization, spillway planning', phase: 'P2', status: 'done' },
      { key: 'roof-catchment-rainwater-storage', label: 'Roof catchment calculation, rainwater storage sizing', phase: 'P2', status: 'done' },
      { key: 'gravity-irrigation-trough-livestock-water', label: 'Gravity-fed irrigation, trough location, livestock water access planning', phase: 'P2', status: 'done' },
      { key: 'wetland-riparian-planning', label: 'Wetland restoration and riparian buffer planning', phase: 'P2', status: 'done' },
      { key: 'water-budget-seasonal-storage', label: 'Water budget calculator, seasonal storage estimates', phase: 'P2', status: 'done' },
      { key: 'water-retention-drought-storm-scores', label: 'Water retention score, drought and storm resilience scores', phase: 'P2', status: 'done' },
      { key: 'water-phasing-dependency-mapping', label: 'Water system phasing and dependency mapping', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 6,
    slug: 'climate-analysis',
    name: 'Solar, Wind & Climate Analysis',
    phases: ['P1', 'P2'],
    status: 'partial',
    features: [
      { key: 'sun-path-visualization', label: 'Sun path visualization, seasonal sun angle simulation', phase: 'P1', status: 'done' },
      { key: 'shade-solar-exposure-heatmap', label: 'Shade analysis, solar exposure heatmap', phase: 'P1', status: 'done' },
      { key: 'structure-tree-shadow-casting', label: 'Structure and tree shadow casting', phase: 'P2', status: 'done' },
      { key: 'solar-panel-placement-zones', label: 'Best solar panel placement zones', phase: 'P2', status: 'partial' },
      { key: 'passive-solar-building-siting', label: 'Passive solar building siting analysis', phase: 'P2', status: 'partial' },
      { key: 'prevailing-wind-shelter', label: 'Prevailing wind visualization, wind shelter analysis', phase: 'P1', status: 'done' },
      { key: 'windbreak-ventilation-corridors', label: 'Windbreak opportunity zones, cold wind exposure, ventilation corridor mapping', phase: 'P2', status: 'partial' },
      { key: 'frost-pocket-heat-sink', label: 'Frost pocket mapping, heat sink identification', phase: 'P2', status: 'done' },
      { key: 'seasonal-comfort-outdoor-seasonality', label: 'Seasonal comfort map, outdoor use seasonality map', phase: 'P2', status: 'done' },
      { key: 'microclimate-adaptation-recommendations', label: 'Microclimate opportunity map, climate adaptation recommendations', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 7,
    slug: 'soil-ecology',
    name: 'Soil, Ecology & Regeneration Diagnostics',
    phases: ['P1', 'P2'],
    status: 'done',
    features: [
      { key: 'soil-type-drainage-ssurgo', label: 'Soil type visualization and drainage classification (from SSURGO)', phase: 'P1', status: 'done' },
      { key: 'ph-organic-compaction-notes', label: 'pH, organic matter, compaction notes fields', phase: 'P1', status: 'done' },
      { key: 'manual-soil-test-entry', label: 'Manual soil test entry, biological activity notes', phase: 'P2', status: 'done' },
      { key: 'soil-restoration-opportunity-map', label: 'Soil restoration opportunity map, disturbed land recovery zones', phase: 'P2', status: 'done' },
      { key: 'mulching-compost-covercrop-zones', label: 'Mulching priority, compost application, cover crop opportunity zones', phase: 'P2', status: 'done' },
      { key: 'silvopasture-foodforest-regen-zones', label: 'Silvopasture, food forest, forest regeneration candidate zones', phase: 'P2', status: 'done' },
      { key: 'native-pollinator-biodiversity', label: 'Native planting, pollinator habitat, biodiversity corridor planning', phase: 'P2', status: 'done' },
      { key: 'invasive-succession-mapping', label: 'Invasive pressure notes, succession stage mapping', phase: 'P2', status: 'done' },
      { key: 'carbon-sequestration-potential', label: 'Carbon sequestration potential map', phase: 'P2', status: 'done' },
      { key: 'regen-stage-intervention-log', label: 'Regeneration stage tagging, intervention log, before/after comparison', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 8,
    slug: 'zoning-allocation',
    name: 'Land Use Zoning & Functional Allocation',
    phases: ['P1', 'P2', 'MT'],
    status: 'partial',
    features: [
      { key: 'draw-custom-zones-naming-color', label: 'Draw custom zones, zone naming and color coding', phase: 'P1', status: 'partial' },
      { key: 'zone-categories-primary-secondary', label: 'Zone categories, primary/secondary use designation', phase: 'P1', status: 'partial' },
      { key: 'zone-sizing-calculator', label: 'Zone sizing calculator', phase: 'P1', status: 'partial' },
      { key: 'auto-suggest-zones', label: 'Auto-suggest zones based on site analysis', phase: 'P2', status: 'partial' },
      { key: 'zone-overlap-conflict-adjacency', label: 'Zone overlap, conflict, and adjacency analysis', phase: 'P2', status: 'done' },
      { key: 'habitation-food-livestock-commons-planning', label: 'Habitation, food production, livestock, commons zone planning', phase: 'P1', status: 'partial' },
      { key: 'prayer-spiritual-zone-planning', label: 'Prayer / spiritual zone planning', phase: 'MT', status: 'partial' },
      { key: 'quiet-contemplation-zone-planning', label: 'Quiet contemplation zone planning', phase: 'MT', status: 'done' },
      { key: 'guest-retreat-education-event-parking', label: 'Guest / retreat, education, event, parking zone planning', phase: 'P2', status: 'partial' },
      { key: 'women-family-privacy-planning', label: 'Women / family privacy planning (where relevant to program design)', phase: 'MT', status: 'done' },
      { key: 'mens-cohort-activity-zone-planning', label: "Men's cohort activity zone planning", phase: 'MT', status: 'done' },
      { key: 'service-maintenance-expansion-preservation', label: 'Service, maintenance, future expansion, preservation zone planning', phase: 'P2', status: 'partial' },
      { key: 'seasonal-temporary-phased-use-zones', label: 'Seasonal, temporary, phased use zones', phase: 'P2', status: 'done' },
      { key: 'land-allocation-summary-report', label: 'Land allocation summary report', phase: 'P2', status: 'partial' },
    ],
  },
  {
    id: 9,
    slug: 'structures-buildings',
    name: 'Structures & Built Environment Planning',
    phases: ['P2', 'P3', 'MT'],
    status: 'partial',
    features: [
      { key: 'place-rotate-resize-structures', label: 'Place, rotate, resize structures on map', phase: 'P2', status: 'partial' },
      { key: 'structure-type-footprint-library', label: 'Structure type assignment, building footprint library', phase: 'P2', status: 'partial' },
      { key: 'earthship-cabin-yurt-pavilion-greenhouse-barn-workshop', label: 'Earthship, cabin, yurt, pavilion, greenhouse, barn, workshop placement', phase: 'P2', status: 'partial' },
      { key: 'prayer-bathhouse-classroom-placement', label: 'Prayer space, bathhouse, classroom placement', phase: 'MT', status: 'done' },
      { key: 'storage-shelter-compost-pumphouse-placement', label: 'Storage, animal shelter, compost, water/pump house placement', phase: 'P2', status: 'done' },
      { key: 'tent-glamping-gathering-firecircle-lookout', label: 'Tent / glamping layout, outdoor gathering, fire circle, lookout placement', phase: 'P2', status: 'done' },
      { key: 'setback-slope-solar-orientation-warnings', label: 'Setback warning, slope warning, solar orientation guide', phase: 'P3', status: 'done' },
      { key: 'wind-view-privacy-noise-analysis', label: 'Wind shelter, view preservation, privacy, noise exposure analysis', phase: 'P3', status: 'done' },
      { key: 'walkability-water-zone-relationship-checks', label: 'Walkability, relationship-to-water, relationship-to-zones checks', phase: 'P3', status: 'done' },
      { key: 'structure-dependency-build-order', label: 'Structure dependency and build order logic', phase: 'P3', status: 'done' },
      { key: 'infrastructure-cost-placeholder-per-structure', label: 'Infrastructure requirement summary, cost placeholder per structure', phase: 'P2', status: 'done' },
      { key: 'alternate-footprint-options', label: 'Alternate footprint options', phase: 'P3', status: 'done' },
      { key: 'multi-story-structure-support', label: 'Multi-story structure support (cost / floor-area scaling)', phase: 'P3', status: 'done' },
    ],
  },
  {
    id: 10,
    slug: 'access-circulation',
    name: 'Access, Circulation & Movement Systems',
    phases: ['P2', 'P3', 'MT'],
    status: 'partial',
    features: [
      { key: 'main-secondary-emergency-service-access', label: 'Main, secondary, emergency, service access planning', phase: 'P2', status: 'partial' },
      { key: 'pedestrian-trail-vehicle-farm-lane', label: 'Pedestrian path, trail, vehicle route, farm lane planning', phase: 'P2', status: 'done' },
      { key: 'animal-corridor-grazing-route', label: 'Animal movement corridor, grazing route planning', phase: 'P2', status: 'partial' },
      { key: 'accessible-route-planning', label: 'Accessible route planning', phase: 'P2', status: 'done' },
      { key: 'route-slope-conflict-detection', label: 'Route slope analysis, conflict detection', phase: 'P3', status: 'partial' },
      { key: 'public-private-circulation-layers', label: 'Public vs private circulation layers', phase: 'P2', status: 'planned' },
      { key: 'arrival-sequence-design', label: 'Arrival sequence design (guest experience path)', phase: 'MT', status: 'partial' },
      { key: 'parking-turning-delivery-checks', label: 'Parking capacity, turning radius, delivery access checks', phase: 'P3', status: 'planned' },
      { key: 'quiet-circulation-routes', label: 'Quiet circulation routes', phase: 'MT', status: 'partial' },
      { key: 'event-flow-night-lighting-safety', label: 'Event flow, night lighting route, safety and visibility checks', phase: 'P3', status: 'planned' },
      { key: 'wayfinding-system-planning', label: 'Wayfinding system planning', phase: 'P3', status: 'done' },
    ],
  },
  {
    id: 11,
    slug: 'livestock-systems',
    name: 'Livestock System Design',
    phases: ['P2', 'P3', 'MT'],
    status: 'partial',
    features: [
      { key: 'species-selection-multi-species-planning', label: 'Species selection planner, multi-species planning', phase: 'P2', status: 'partial' },
      { key: 'rotational-grazing-cell-paddock-drawing', label: 'Rotational grazing cell design, paddock boundary drawing', phase: 'P2', status: 'partial' },
      { key: 'paddock-sizing-stocking-density', label: 'Paddock sizing calculator, stocking density assumptions', phase: 'P2', status: 'done' },
      { key: 'recovery-period-rotation-schedule', label: 'Recovery period planner, rotation schedule view', phase: 'P2', status: 'partial' },
      { key: 'water-shelter-shade-access', label: 'Water point, shelter, and shade access planning', phase: 'P2', status: 'partial' },
      { key: 'chicken-rabbit-pig-tractor-zones', label: 'Chicken tractor, rabbit tractor, pig disturbance zone planning', phase: 'P2', status: 'done' },
      { key: 'fencing-gate-corridor-chute', label: 'Fencing layout, gate placement, corridor/chute planning', phase: 'P2', status: 'planned' },
      { key: 'predator-risk-zone-map', label: 'Predator risk zone map', phase: 'P3', status: 'partial' },
      { key: 'fertility-manure-impact-heatmap', label: 'Fertility distribution heatmap, manure impact zone planning', phase: 'P3', status: 'done' },
      { key: 'browse-pressure-overgrazing-risk', label: 'Browse pressure analysis, overgrazing risk detection', phase: 'P3', status: 'partial' },
      { key: 'livestock-land-fit-enterprise-zone', label: 'Livestock-to-land fit score, enterprise-by-zone allocation', phase: 'P3', status: 'done' },
      { key: 'species-human-conflict-warnings', label: 'Species conflict and human-animal movement conflict warnings', phase: 'P3', status: 'done' },
      { key: 'guest-safe-livestock-buffer', label: 'Guest-safe livestock buffer planning', phase: 'MT', status: 'partial' },
      { key: 'welfare-notes-infrastructure-phasing', label: 'Animal welfare notes, livestock infrastructure phasing', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 12,
    slug: 'crops-agroforestry',
    name: 'Crop, Orchard & Agroforestry Design',
    phases: ['P2', 'P3'],
    status: 'partial',
    features: [
      { key: 'orchard-row-garden-foodforest-placement', label: 'Orchard, row crop, garden bed, food forest placement planning', phase: 'P2', status: 'partial' },
      { key: 'agroforestry-windbreak-shelterbelt-silvopasture', label: 'Agroforestry band, windbreak, shelterbelt, silvopasture planning', phase: 'P2', status: 'partial' },
      { key: 'pollinator-strip-companion-zone-notes', label: 'Pollinator strip, companion planting zone notes', phase: 'P2', status: 'done' },
      { key: 'tree-spacing-calculator', label: 'Tree spacing calculator', phase: 'P2', status: 'partial' },
      { key: 'canopy-maturity-root-overlap', label: 'Canopy maturity simulation, root zone overlap visualization', phase: 'P3', status: 'planned' },
      { key: 'shade-succession-forecasting', label: 'Shade succession forecasting', phase: 'P3', status: 'planned' },
      { key: 'frost-safe-orchard-drainage-placement', label: 'Frost-safe orchard zone detection, drainage-sensitive placement', phase: 'P2', status: 'done' },
      { key: 'species-suitability-water-demand', label: 'Species suitability notes, water-demand classification', phase: 'P2', status: 'done' },
      { key: 'access-harvest-irrigation-tie-in', label: 'Access-to-harvest and irrigation tie-in planning', phase: 'P2', status: 'done' },
      { key: 'nursery-compost-proximity', label: 'Nursery zone, compost proximity planning', phase: 'P2', status: 'done' },
      { key: 'seasonal-productivity-multilayer', label: 'Seasonal productivity map, multi-layer planting visualization', phase: 'P3', status: 'done' },
      { key: 'year-to-maturity-yield-placeholder', label: 'Year-to-maturity phasing, yield placeholder estimates', phase: 'P3', status: 'partial' },
    ],
  },
  {
    id: 13,
    slug: 'utilities-energy',
    name: 'Utilities, Energy & Support Systems',
    phases: ['P2', 'P3'],
    status: 'done',
    features: [
      { key: 'solar-battery-generator-placement', label: 'Solar array, battery/power room, generator backup placement', phase: 'P2', status: 'done' },
      { key: 'water-tank-well-greywater-planning', label: 'Water tank, well/pump, greywater zone planning', phase: 'P2', status: 'done' },
      { key: 'blackwater-septic-toilet', label: 'Blackwater / composting toilet, septic note layer', phase: 'P2', status: 'done' },
      { key: 'rain-catchment-corridor-lighting', label: 'Rain catchment tie-in, utility corridor, lighting zone planning', phase: 'P2', status: 'done' },
      { key: 'firewood-waste-compost-biochar', label: 'Firewood flow, waste sorting, compost, biochar station planning', phase: 'P2', status: 'done' },
      { key: 'tool-maintenance-laundry', label: 'Tool storage, maintenance yard, laundry/wash station planning', phase: 'P2', status: 'done' },
      { key: 'energy-demand-notes', label: 'Energy demand placeholder notes, utility dependency mapping', phase: 'P3', status: 'done' },
      { key: 'off-grid-readiness-redundancy', label: 'Off-grid readiness score, redundancy planning', phase: 'P3', status: 'done' },
      { key: 'utility-phasing', label: 'Utility phasing', phase: 'P2', status: 'done' },
    ],
  },
  {
    id: 14,
    slug: 'moontrance-vision',
    name: 'Moontrance Vision Layer & Concept Overlay',
    phases: ['P2', 'P3', 'MT'],
    status: 'partial',
    features: [
      { key: 'toggle-current-vs-vision', label: 'Toggle current land vs vision', phase: 'P2', status: 'partial' },
      { key: 'before-after-concept-masterplan-overlay', label: 'Before / after comparison, concept masterplan overlay', phase: 'P2', status: 'partial' },
      { key: 'stage-by-stage-reveal-narrative', label: 'Stage-by-stage reveal, design narrative mode', phase: 'P2', status: 'partial' },
      { key: 'signs-in-creation-interpretive-mode', label: "'Signs in creation' interpretive mode", phase: 'MT', status: 'done' },
      { key: 'spiritual-educational-storytelling-layer', label: 'Spiritual / educational storytelling layer', phase: 'MT', status: 'partial' },
      { key: 'service-stewardship-framing-panels', label: 'Service / stewardship framing panels', phase: 'MT', status: 'partial' },
      { key: 'feature-explanations-tied-to-purpose', label: 'Feature explanations tied to purpose, not just function', phase: 'MT', status: 'planned' },
      { key: 'guided-flyover-scene-bookmarks', label: 'Guided flyover mode, scene bookmarks', phase: 'P3', status: 'planned' },
      { key: 'curated-visitor-journey-camera-angles', label: 'Curated visitor journey, presentation-safe camera angles', phase: 'P3', status: 'planned' },
      { key: 'vision-board-media-reference-imagery', label: 'Vision board media embedding, reference imagery per feature', phase: 'P3', status: 'planned' },
      { key: 'why-what-replaces-what-stage-panels', label: "'Why this is here', 'What this replaces', 'What stage this appears' panels", phase: 'P3', status: 'planned' },
      { key: 'problem-solves-dependencies-panels', label: "'What problem this solves', 'What it depends on' panels", phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 15,
    slug: 'timeline-phasing',
    name: 'Timeline, Phasing & Staged Buildout',
    phases: ['P2', 'P3'],
    status: 'partial',
    features: [
      { key: 'timeline-slider-year-modes', label: 'Timeline slider, Year 0 / Year 1 / Year 3 / Year 5 / Full Vision modes', phase: 'P2', status: 'partial' },
      { key: 'custom-phase-dependencies-milestones', label: 'Custom phase creation, stage dependencies, milestone view', phase: 'P2', status: 'done' },
      { key: 'build-sequence-infrastructure-water-regen-revenue', label: 'Build sequence map, infrastructure/water/regeneration/revenue-first sequencing', phase: 'P2', status: 'done' },
      { key: 'temporary-vs-permanent-seasonal', label: 'Temporary vs permanent elements, seasonal phase view', phase: 'P2', status: 'done' },
      { key: 'cost-labor-material-per-phase', label: 'Cost, labor, material need by phase', phase: 'P2', status: 'done' },
      { key: 'permit-dependencies-readiness-checklist', label: 'Permit dependency warnings, readiness checklist per phase', phase: 'P3', status: 'done' },
      { key: 'phase-completion-tracking-notes', label: 'Phase completion tracking and notes', phase: 'P2', status: 'done' },
      { key: 'scenario-phasing-alternatives', label: 'Scenario-based phasing alternatives', phase: 'P3', status: 'partial' },
      { key: 'path-modes-fastest-lowest-cost-regen-investor', label: "'Fastest feasible path', 'Lowest cost path', 'Most regenerative path', 'Investor presentation path' modes", phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 16,
    slug: 'simulation-scenarios',
    name: 'Simulation & Scenario Modeling',
    phases: ['P3', 'P4'],
    status: 'partial',
    features: [
      { key: 'water-flood-drought-scenario-sim', label: 'Water flow, flood, drought scenario simulation', phase: 'P3', status: 'done' },
      { key: 'wind-shade-tree-canopy-sim', label: 'Wind exposure, shade growth, tree maturity, canopy expansion simulation', phase: 'P3', status: 'done' },
      { key: 'erosion-grazing-recovery-modeling', label: 'Erosion mitigation, grazing pressure, recovery timeline modeling', phase: 'P3', status: 'done' },
      { key: 'carrying-capacity-yield-projections', label: 'Carrying capacity scenario, yield projection placeholders', phase: 'P3', status: 'done' },
      { key: 'visitor-event-parking-overflow-sim', label: 'Visitor traffic, event load, parking overflow scenario modeling', phase: 'P3', status: 'planned' },
      { key: 'build-cost-revenue-ranges', label: 'Build cost and revenue scenario ranges', phase: 'P3', status: 'partial' },
      { key: 'best-base-worst-case-scenarios', label: 'Best-case / base-case / worst-case scenarios', phase: 'P3', status: 'done' },
      { key: 'climate-shift-overlays', label: 'Climate shift scenario overlays', phase: 'P4', status: 'planned' },
      { key: 'fire-emergency-infrastructure-failure-water-shortage', label: 'Fire / emergency, infrastructure failure, water shortage scenarios', phase: 'P3', status: 'planned' },
      { key: 'layout-option-a-b-c-comparison', label: 'Alternate layout and design option A/B/C comparison', phase: 'P3', status: 'partial' },
      { key: 'sensitivity-analysis-by-assumption', label: 'Sensitivity analysis by assumption', phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 17,
    slug: 'design-rules',
    name: 'Rule-Based Design Intelligence',
    phases: ['P3', 'MT'],
    status: 'partial',
    features: [
      { key: 'rules-layer-siting-logic', label: 'Rules layer for siting logic', phase: 'P3', status: 'partial' },
      { key: 'siting-rules-structure-orchard-water-grazing-quiet-sacred', label: 'Structure, orchard, water, grazing, quiet zone, sacred zone siting rules', phase: 'P3', status: 'partial' },
      { key: 'siting-rules-privacy-solar-access-safety', label: 'Guest privacy, solar access, access efficiency, safety buffer rules', phase: 'P3', status: 'partial' },
      { key: 'ecological-wildlife-protection-rules', label: 'Ecological and wildlife protection rules', phase: 'P3', status: 'done' },
      { key: 'rule-scoring-conflict-alerts-explainable-recommendations', label: 'Rule scoring, conflict alerts, explainable recommendation layer', phase: 'P3', status: 'partial' },
      { key: 'why-this-suggestion-was-made', label: "'Why this suggestion was made' output (see Section 0d AI guardrails)", phase: 'P3', status: 'done' },
      { key: 'user-adjustable-design-priority-weight-sliders', label: 'User-adjustable design priority weight sliders', phase: 'P3', status: 'planned' },
      { key: 'ogden-specific-design-template', label: 'OGDEN-specific design template', phase: 'MT', status: 'planned' },
      { key: 'design-templates-farm-retreat-conservation-homestead-multi-enterprise', label: 'Farm-only, retreat/education, conservation-first, homestead, multi-enterprise templates', phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 18,
    slug: 'ai-design-support',
    name: 'AI-Assisted Design Support',
    phases: ['P3'],
    status: 'stub',
    features: [
      { key: 'ai-site-summary', label: 'AI site summary (with data source attribution and confidence level)', phase: 'P3', status: 'partial' },
      { key: 'ai-constraint-opportunity-summaries', label: 'AI constraint and opportunity summaries', phase: 'P3', status: 'done' },
      { key: 'ai-feature-placement-suggestions', label: 'AI feature placement suggestions (with explainability output)', phase: 'P3', status: 'planned' },
      { key: 'ai-phased-build-water-grazing-orchard-strategies', label: 'AI phased build, water strategy, grazing strategy, orchard strategy suggestions', phase: 'P3', status: 'planned' },
      { key: 'ai-risk-warnings-ecological-interpretation', label: 'AI risk warnings and ecological interpretation', phase: 'P3', status: 'planned' },
      { key: 'ai-design-brief-investor-landowner-pitch', label: 'AI design brief, investor summary, landowner pitch generation (editable, clearly labeled as AI draft)', phase: 'P3', status: 'planned' },
      { key: 'ai-educational-explanation-checklists', label: 'AI educational explanation and checklist generation', phase: 'P3', status: 'planned' },
      { key: 'ai-assumptions-unanswered-questions-data-gap-detector', label: 'AI assumptions extractor, unanswered questions detector, data gap detector', phase: 'P3', status: 'planned' },
      { key: 'ai-needs-site-visit-flags', label: "AI 'needs site visit' flags (triggered at confidence below Medium)", phase: 'P3', status: 'planned' },
      { key: 'ai-alternative-layout-rationale', label: 'AI alternative layout and design rationale output', phase: 'P3', status: 'planned' },
      { key: 'ai-output-rating-feedback', label: 'AI output rating / feedback system', phase: 'P3', status: 'partial' },
    ],
  },
  {
    id: 19,
    slug: 'education-interpretive',
    name: 'Educational & Interpretive Layer',
    phases: ['P3', 'P4', 'MT'],
    status: 'partial',
    features: [
      { key: 'clickable-hotspots-side-panel', label: 'Clickable hotspots, side panel explanations', phase: 'P3', status: 'partial' },
      { key: 'rationale-cards-purpose-meaning', label: 'Feature-specific rationale cards tied to purpose and meaning', phase: 'MT', status: 'planned' },
      { key: 'ecology-water-livestock-agroforestry-modes', label: 'Ecology, water, livestock, agroforestry explanation modes', phase: 'MT', status: 'planned' },
      { key: 'spiritual-symbolism-regeneration-modes', label: 'Spiritual symbolism and regeneration phase explanation modes', phase: 'MT', status: 'planned' },
      { key: 'why-here-not-there-panels', label: "'Why here, not there?', 'What problem does this solve?', 'What happens if omitted?' panels", phase: 'P3', status: 'partial' },
      { key: 'passive-learning-tour-walkthrough', label: 'Passive learning tour, guided walkthrough mode', phase: 'P4', status: 'done' },
      { key: 'voiceover-script-slide-export', label: 'Voiceover-ready script export, slide presentation mode', phase: 'P4', status: 'planned' },
      { key: 'public-stakeholder-education-modes', label: 'Public and stakeholder education modes', phase: 'P4', status: 'planned' },
      { key: 'operator-training-student-quiz-modes', label: 'Training mode for operators, quiz/checkpoint mode for students', phase: 'P4', status: 'planned' },
      { key: 'before-after-change-over-time', label: 'Before/after educational storytelling, change-over-time panels', phase: 'MT', status: 'planned' },
    ],
  },
  {
    id: 20,
    slug: 'collaboration-review',
    name: 'Collaboration, Teamwork & Review',
    phases: ['P3'],
    status: 'partial',
    features: [
      { key: 'multi-user-rbac', label: 'Multi-user access, role-based permissions (Owner, Designer, Reviewer, Viewer)', phase: 'P3', status: 'partial' },
      { key: 'commenting-on-map-and-features', label: 'Commenting on map and on specific features', phase: 'P3', status: 'partial' },
      { key: 'suggest-edit-markup-threads', label: 'Suggest edit mode, markup tools, discussion threads', phase: 'P3', status: 'planned' },
      { key: 'task-assignment-approval-revisions', label: 'Task assignment, approval workflow, revision requests', phase: 'P3', status: 'planned' },
      { key: 'version-compare-changelog-snapshots', label: 'Version comparison, change log, snapshot sharing', phase: 'P3', status: 'planned' },
      { key: 'internal-vs-public-views', label: 'Internal vs public views, stakeholder presentation links', phase: 'P3', status: 'planned' },
      { key: 'team-activity-feed', label: 'Team activity feed, review checklist, sign-off workflow by stage', phase: 'P3', status: 'partial' },
      { key: 'export-comments-with-report', label: 'Export comments with report', phase: 'P3', status: 'planned' },
      { key: 'view-only-shareable-link', label: 'View-only shareable link (no account required — see Section 0g)', phase: 'P3', status: 'planned' },
      { key: 'stakeholder-community-review-mode', label: 'Simplified stakeholder view and community review mode', phase: 'P3', status: 'planned' },
      { key: 'meeting-presentation-mode', label: 'Meeting presentation mode', phase: 'P3', status: 'done' },
    ],
  },
  {
    id: 21,
    slug: 'decision-feasibility',
    name: 'Decision Support & Feasibility',
    phases: ['P2', 'P3'],
    status: 'partial',
    features: [
      { key: 'feasibility-summary', label: 'Feasibility summary, constraint checklist, missing information checklist', phase: 'P2', status: 'done' },
      { key: 'regulatory-risk-notes', label: 'Regulatory risk notes (see Section 0e for full regulatory layer)', phase: 'P2', status: 'done' },
      { key: 'access-water-ag-livestock-feasibility', label: 'Access, water, agricultural, livestock feasibility notes', phase: 'P2', status: 'planned' },
      { key: 'hospitality-education-energy-feasibility', label: 'Hospitality, education, energy feasibility notes', phase: 'P2', status: 'planned' },
      { key: 'terrain-construction-difficulty', label: 'Terrain construction difficulty notes', phase: 'P2', status: 'planned' },
      { key: 'capital-intensity-operational-complexity', label: 'Capital intensity estimate, operational complexity score', phase: 'P2', status: 'planned' },
      { key: 'seasonal-vulnerability-phasing-realism', label: 'Seasonal vulnerability score, phasing realism score', phase: 'P2', status: 'planned' },
      { key: 'good-fit-poor-fit-best-use', label: "'Good fit / poor fit', 'Best use of this land', 'Not recommended uses' summaries", phase: 'P2', status: 'partial' },
      { key: 'what-must-be-solved-first', label: "'What must be solved first', 'What can wait' summaries", phase: 'P2', status: 'partial' },
      { key: 'maintenance-complexity-score', label: 'Maintenance complexity score', phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 22,
    slug: 'economic-modeling',
    name: 'Economic Planning & Business Modeling',
    phases: ['P2', 'P3'],
    status: 'partial',
    features: [
      { key: 'cost-estimate-by-feature-phase', label: 'Cost estimate by feature and by phase (with regional benchmarks — see Section 0f)', phase: 'P2', status: 'partial' },
      { key: 'revenue-stream-tagging-enterprise-mapping', label: 'Revenue stream tagging, enterprise mapping', phase: 'P2', status: 'partial' },
      { key: 'enterprise-revenue-placeholders', label: 'Orchard, livestock, retreat, education, agritourism revenue placeholders', phase: 'P2', status: 'planned' },
      { key: 'regional-cost-database', label: 'Regional cost database with low/mid/high ranges (Section 0f)', phase: 'P3', status: 'planned' },
      { key: 'cost-override-contractor-bid-import', label: 'User cost override and contractor bid import', phase: 'P3', status: 'planned' },
      { key: 'cost-sensitivity-hidden-costs-contingency', label: 'Cost sensitivity sliders, hidden cost flags, contingency recommendations', phase: 'P3', status: 'planned' },
      { key: 'enterprise-revenue-templates-ramp-timeline', label: 'Enterprise revenue templates with ramp timeline modeling', phase: 'P3', status: 'planned' },
      { key: 'cashflow-sequence-chart-break-even', label: 'Cashflow sequence chart, break-even analysis', phase: 'P3', status: 'partial' },
      { key: 'mission-weighted-donor-grant-income', label: 'Mission-weighted and donor/grant income modeling', phase: 'P3', status: 'done' },
      { key: 'overbuilt-for-revenue-lean-mvp', label: "'Overbuilt for revenue' AI warning, Lean MVP path view", phase: 'P3', status: 'planned' },
      { key: 'investor-summary-landowner-partnership', label: 'Investor summary dashboard, landowner partnership summary', phase: 'P3', status: 'partial' },
      { key: 'grant-readiness-total-cost-of-ownership', label: 'Grant-readiness checklist, total cost of ownership view', phase: 'P3', status: 'planned' },
    ],
  },
  {
    id: 23,
    slug: 'reporting-export',
    name: 'Reporting, Export & Presentation',
    phases: ['P2', 'P3', 'P4'],
    status: 'partial',
    features: [
      { key: 'pdf-site-assessment-export', label: 'PDF site assessment export', phase: 'P2', status: 'partial' },
      { key: 'design-brief-feature-schedule-export', label: 'Design brief export, feature schedule export', phase: 'P2', status: 'partial' },
      { key: 'phasing-cost-investor-landowner-exports', label: 'Phasing report, cost summary, investor presentation, landowner pitch exports', phase: 'P3', status: 'planned' },
      { key: 'educational-booklet-export', label: 'Educational booklet export', phase: 'P3', status: 'planned' },
      { key: 'gis-kml-geojson-export', label: 'GIS layer export, KML / GeoJSON export', phase: 'P3', status: 'partial' },
      { key: 'image-export-screenshot', label: 'Image export, screenshot capture', phase: 'P3', status: 'partial' },
      { key: 'branded-presentation-print-layout', label: 'Branded presentation mode, print layout mode', phase: 'P3', status: 'done' },
      { key: 'white-label-export-mode', label: 'White-label export mode', phase: 'P3', status: 'planned' },
      { key: 'flyover-video-export', label: 'Flyover video export', phase: 'P4', status: 'planned' },
      { key: 'qr-share-embed-website', label: 'QR-share link, embed view on website', phase: 'P4', status: 'planned' },
      { key: 'interactive-public-share-readonly-client-handoff', label: 'Interactive public share mode, read-only client handoff mode', phase: 'P4', status: 'planned' },
    ],
  },
  {
    id: 24,
    slug: 'mobile-fieldwork',
    name: 'Mobile, Fieldwork & Site Visit Tools',
    phases: ['P2', 'P4'],
    status: 'partial',
    features: [
      { key: 'mobile-friendly-map-gps', label: 'Mobile-friendly map view, GPS location on site', phase: 'P2', status: 'partial' },
      { key: 'field-note-geotagged-photo', label: 'Field note and geotagged photo capture', phase: 'P2', status: 'partial' },
      { key: 'voice-memo-site-checklist', label: 'Voice memo attachment, site checklist mode', phase: 'P2', status: 'planned' },
      { key: 'offline-field-mode-sync', label: 'Offline field mode and sync (see Section 0g)', phase: 'P2', status: 'planned' },
      { key: 'soil-water-structure-issue-logging', label: 'Soil sample, water issue, structure issue point logging', phase: 'P4', status: 'planned' },
      { key: 'walk-route-quick-annotation', label: 'Walk route recording, quick annotation mode', phase: 'P4', status: 'planned' },
      { key: 'on-site-measurement-logging', label: 'On-site measurement logging', phase: 'P4', status: 'planned' },
      { key: 'site-visit-report-generation', label: 'Site visit report generation', phase: 'P4', status: 'planned' },
      { key: 'punch-list-site-verification', label: 'Punch-list creation, site verification against design', phase: 'P4', status: 'planned' },
      { key: 'as-built-update-mode', label: 'As-built update mode', phase: 'P4', status: 'planned' },
    ],
  },
  {
    id: 25,
    slug: 'reusable-frameworks',
    name: 'Template System & Reusable Design Frameworks',
    phases: ['P3', 'P4', 'MT'],
    status: 'stub',
    features: [
      { key: 'project-property-design-style-templates', label: 'Project, property type, design style templates', phase: 'P3', status: 'planned' },
      { key: 'ogden-template', label: 'OGDEN template', phase: 'MT', status: 'planned' },
      { key: 'regen-farm-retreat-homestead-edu-templates', label: 'Regenerative farm, retreat center, homestead, educational farm templates', phase: 'P3', status: 'planned' },
      { key: 'livestock-water-degraded-land-templates', label: 'Livestock-first, water-retention-first, degraded land restoration templates', phase: 'P3', status: 'planned' },
      { key: 'mens-cohort-campus-template', label: "Men's cohort campus template", phase: 'MT', status: 'planned' },
      { key: 'family-oriented-community-template', label: 'Family-oriented community template', phase: 'MT', status: 'planned' },
      { key: 'saved-bundles-rules-hotspots-phases-costs', label: 'Saved feature bundles, rule sets, hotspot sets, phase structures, cost models', phase: 'P3', status: 'planned' },
      { key: 'template-duplication-locking-governance', label: 'Template duplication and locking / governance', phase: 'P3', status: 'partial' },
      { key: 'template-marketplace', label: 'Template marketplace', phase: 'P4', status: 'planned' },
    ],
  },
  {
    id: 26,
    slug: 'admin-governance',
    name: 'Administration, Governance & Data Integrity',
    phases: ['P1', 'P2'],
    status: 'partial',
    features: [
      { key: 'user-management', label: 'User management', phase: 'P1', status: 'partial' },
      { key: 'workspace-management', label: 'Workspace management', phase: 'P1', status: 'partial' },
      { key: 'organization-settings', label: 'Organization settings', phase: 'P1', status: 'partial' },
      { key: 'access-controls', label: 'Access controls', phase: 'P1', status: 'done' },
      { key: 'project-ownership-transfer', label: 'Project ownership transfer', phase: 'P1', status: 'planned' },
      { key: 'backup-and-restore', label: 'Backup and restore', phase: 'P1', status: 'planned' },
      { key: 'audit-log', label: 'Audit log', phase: 'P1', status: 'partial' },
      { key: 'data-provenance-notes', label: 'Data provenance notes', phase: 'P2', status: 'planned' },
      { key: 'source-citation-tracking', label: 'Source citation tracking', phase: 'P2', status: 'planned' },
      { key: 'assumption-tracking', label: 'Assumption tracking', phase: 'P2', status: 'planned' },
      { key: 'confidence-rating-per-analysis', label: 'Confidence rating per analysis', phase: 'P2', status: 'done' },
      { key: 'incomplete-data-warnings', label: 'Incomplete-data warnings', phase: 'P2', status: 'partial' },
      { key: 'manual-override-logging', label: 'Manual override logging', phase: 'P2', status: 'planned' },
      { key: 'qa-checklist', label: 'QA checklist', phase: 'P2', status: 'planned' },
      { key: 'design-review-checklist', label: 'Design review checklist', phase: 'P2', status: 'planned' },
      { key: 'locked-approval-states', label: 'Locked approval states', phase: 'P2', status: 'planned' },
      { key: 'archive-delete-recover-projects', label: 'Archive / delete / recover projects', phase: 'P2', status: 'planned' },
      { key: 'naming-conventions', label: 'Naming conventions', phase: 'P2', status: 'planned' },
      { key: 'metadata-management', label: 'Metadata management', phase: 'P2', status: 'partial' },
    ],
  },
  {
    id: 27,
    slug: 'public-portal',
    name: 'Public Experience & Storytelling Portal',
    phases: ['P4', 'MT'],
    status: 'partial',
    features: [
      { key: 'public-landing-page', label: 'Public landing page for project', phase: 'P4', status: 'done' },
      { key: 'interactive-public-property-view', label: 'Interactive public property view, guided public tour', phase: 'P4', status: 'planned' },
      { key: 'stage-reveal-story', label: 'Stage reveal story, mission story overlay', phase: 'MT', status: 'planned' },
      { key: 'donation-support-cta', label: 'Donation / support CTA integration', phase: 'P4', status: 'planned' },
      { key: 'inquiry-interest-forms', label: 'Inquiry, investor interest, landowner interest, volunteer interest form integration', phase: 'P4', status: 'planned' },
      { key: 'educational-tour-mode', label: 'Educational tour mode', phase: 'MT', status: 'planned' },
      { key: 'public-safe-data-masking', label: 'Public-safe data masking, curated hotspots only mode', phase: 'P4', status: 'partial' },
      { key: 'branded-storytelling-scenes', label: 'Branded storytelling scenes, narrated site journey', phase: 'MT', status: 'planned' },
      { key: 'before-after-visual-slider', label: 'Before / after visual slider', phase: 'MT', status: 'planned' },
      { key: 'narrative-sections', label: "'Why this place', 'How it evolves', 'What you can support' narrative sections", phase: 'MT', status: 'planned' },
    ],
  },
  {
    id: 28,
    slug: 'future-geospatial',
    name: 'Advanced Geospatial / Future-Ready Features',
    phases: ['FUTURE'],
    status: 'stub',
    features: [
      { key: 'lidar-drone-photogrammetry-import', label: 'LiDAR / drone point cloud / photogrammetry mesh import', phase: 'FUTURE', status: 'planned' },
      { key: 'hi-res-terrain-3d-tiles', label: 'High-resolution terrain mesh replacement + 3D tiles support', phase: 'FUTURE', status: 'planned' },
      { key: 'sensor-data-integration', label: 'Sensor data integration (soil, water, weather, grazing)', phase: 'FUTURE', status: 'planned' },
      { key: 'satellite-revisit-change-detection', label: 'Satellite revisit monitoring + change detection over time', phase: 'FUTURE', status: 'planned' },
      { key: 'vegetation-health-degradation-detection', label: 'Vegetation health and land degradation detection', phase: 'FUTURE', status: 'planned' },
      { key: 'carbon-monitoring-integrations', label: 'Carbon monitoring integrations', phase: 'FUTURE', status: 'planned' },
      { key: 'ar-vr-walkthrough', label: 'AR site walkthrough + VR immersive walkthrough modes', phase: 'FUTURE', status: 'planned' },
      { key: 'multi-property-corridor-planning', label: 'Multi-property regional + corridor-level landscape planning', phase: 'FUTURE', status: 'planned' },
      { key: 'portfolio-dashboard', label: 'Portfolio dashboard for many sites', phase: 'FUTURE', status: 'planned' },
    ],
  },
  {
    id: 29,
    slug: 'moontrance-identity',
    name: 'Moontrance-Specific Features',
    phases: ['MT'],
    status: 'partial',
    features: [
      { key: 'prayer-pavilion-quiet-reflection-siting', label: '[P1] Prayer pavilion siting logic and quiet reflection zone planning', phase: 'MT', status: 'partial' },
      { key: 'scenic-overlook-community-commons', label: '[P1] Scenic overlook and community commons planning', phase: 'MT', status: 'planned' },
      { key: 'mens-cohort-family-expansion-zones', label: "[P2] Men's cohort training zone and family expansion stage planning", phase: 'MT', status: 'planned' },
      { key: 'hospitality-sequence-planning', label: '[P2] Hospitality sequence planning', phase: 'MT', status: 'planned' },
      { key: 'islamic-adab-privacy-logic', label: '[P2] Islamic-adab-conscious privacy logic', phase: 'MT', status: 'planned' },
      { key: 'educational-immersion-route', label: '[P2] Educational immersion route planning', phase: 'MT', status: 'done' },
      { key: 'regeneration-remembrance-storytelling', label: '[P2] Regeneration + remembrance storytelling layer', phase: 'MT', status: 'planned' },
      { key: 'staged-vision-raw-to-heaven', label: '[P2] Staged vision from raw land to heaven-like experience', phase: 'MT', status: 'partial' },
      { key: 'signs-in-creation-interpretive', label: "[P3] 'Signs in creation' interpretive mode", phase: 'MT', status: 'planned' },
      { key: 'service-stewardship-framing', label: '[P3] Service / stewardship framing panels', phase: 'MT', status: 'planned' },
      { key: 'purpose-function-feature-explanations', label: '[P3] Feature explanations tied to purpose, not just function', phase: 'MT', status: 'planned' },
      { key: 'guest-experience-path', label: '[P3] Guest experience path design', phase: 'MT', status: 'planned' },
      { key: 'dawn-sunset-viewpoints', label: '[P2] Dawn / sunset experience viewpoint planning', phase: 'MT', status: 'partial' },
      { key: 'fire-circle-gathering-placement', label: '[P2] Fire circle / gathering placement logic', phase: 'MT', status: 'planned' },
      { key: 'seasonal-retreat-outdoor-learning', label: '[P3] Seasonal retreat mode, outdoor learning station planning', phase: 'MT', status: 'planned' },
      { key: 'water-land-worship-integration', label: '[P2] Water, land, and worship integration layer', phase: 'MT', status: 'planned' },
    ],
  },
  // All 29 sections populated. Appended historically via
  // `apps/api/scripts/scaffold-section.ts`; do not hand-edit stubs in.
];

/** Lookup by section id. */
export function getSection(id: number): FeatureSection | undefined {
  return FEATURE_SECTIONS.find((s) => s.id === id);
}

/** Lookup by slug. */
export function getSectionBySlug(slug: string): FeatureSection | undefined {
  return FEATURE_SECTIONS.find((s) => s.slug === slug);
}

/** Find a feature item across all sections. */
export function getFeature(key: string): FeatureItem | undefined {
  for (const section of FEATURE_SECTIONS) {
    const found = section.features.find((f) => f.key === key);
    if (found) return found;
  }
  return undefined;
}

/**
 * True when `candidate` is at or below `max` in ordinal phase ranking.
 * MT is never included by P-tag max; gate MT separately.
 */
export function phaseAtMost(candidate: PhaseTag, max: PhaseTag): boolean {
  if (candidate === 'MT' || max === 'MT') return candidate === max;
  if (candidate === 'FUTURE' || max === 'FUTURE') return candidate === max;
  return PHASE_ORDER[candidate] <= PHASE_ORDER[max];
}

/**
 * True when a feature key should be visible given a phase ceiling.
 * Unknown keys return `true` — a missing manifest entry should not hide
 * an existing UI surface. This is the safe default during incremental
 * manifest population (Sections 2-30 are added over time).
 */
export function isFeatureVisible(key: string, phaseMax: PhaseTag = 'P4'): boolean {
  const feat = getFeature(key);
  if (!feat) return true;
  return phaseAtMost(feat.phase, phaseMax);
}
