// generate-stratum1-objectives.ts
//
// Read-only generator: emit a single, scannable markdown reference of EVERY
// Stratum 1 ("Project Foundation") objective across all encoded catalogues,
// with rich detail per objective and its checklist (the "tasks").
//
// It reads the same pure catalogue data the live Plan/Act spine consumes — no
// re-derivation, no schema change:
//
//   - allCatalogueObjectives()  -> every standalone objective across all
//                                   catalogues (universal + all primaries + all
//                                   secondary additive), deduped by id, each
//                                   stamped with `source` + `sourceTypeId`.
//   - PLAN_STRATA               -> stratum title + theme summary.
//   - PROJECT_TYPES             -> human display label per ProjectTypeId.
//
// NOTE: patch-injected items are not standalone objectives — they live inside a
// target objective's checklist only in the FULLY-RESOLVED-with-secondary set,
// so they are intentionally absent here. This listing is the authored standalone
// surface, not the resolved-per-project set.
//
// `@ogden/shared` is not symlinked at the repo root, so this imports the package
// source by relative path (matching audit-act-objective-coverage.ts).
//
// Run:  npx tsx scripts/generate-stratum1-objectives.ts
// Out:  scripts/audit-out/stratum1-objectives.md

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  allCatalogueObjectives,
  PLAN_STRATA,
  PROJECT_TYPES,
  type PlanStratumObjective,
  type ProjectTypeId,
} from '../packages/shared/src/index.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(HERE, 'audit-out/stratum1-objectives.md');

const S1_ID = 's1-project-foundation';
const stratum = PLAN_STRATA.find((s) => s.id === S1_ID)!;

const labelFor = (id: ProjectTypeId | undefined): string =>
  PROJECT_TYPES.find((t) => t.id === id)?.label ?? String(id ?? 'unknown');

// ---------------------------------------------------------------------------
// Collect & group the Stratum 1 objectives.
// ---------------------------------------------------------------------------

const s1 = allCatalogueObjectives()
  .filter((o) => o.stratumId === S1_ID)
  .slice()
  .sort((a, b) => (a.ref ?? a.id).localeCompare(b.ref ?? b.id));

interface Group {
  key: string;
  heading: string;
  objectives: PlanStratumObjective[];
}

const groups: Group[] = [];

// Universal first.
const universal = s1.filter((o) => o.source === 'universal');
if (universal.length) {
  groups.push({ key: 'universal', heading: 'Universal (every project)', objectives: universal });
}

// Then per project type, in taxonomy order: primary layer, then secondary layer.
for (const type of PROJECT_TYPES) {
  const primary = s1.filter((o) => o.source === 'primary' && o.sourceTypeId === type.id);
  if (primary.length) {
    groups.push({
      key: `${type.id}:primary`,
      heading: `${type.label} — primary`,
      objectives: primary,
    });
  }
  const secondary = s1.filter((o) => o.source === 'secondary' && o.sourceTypeId === type.id);
  if (secondary.length) {
    groups.push({
      key: `${type.id}:secondary`,
      heading: `${type.label} — secondary layer`,
      objectives: secondary,
    });
  }
}

// Safety net: any objective whose source/sourceTypeId did not map to a group.
const grouped = new Set(groups.flatMap((g) => g.objectives.map((o) => o.id)));
const ungrouped = s1.filter((o) => !grouped.has(o.id));
if (ungrouped.length) {
  groups.push({ key: 'ungrouped', heading: 'Unclassified', objectives: ungrouped });
}

// ---------------------------------------------------------------------------
// Render markdown.
// ---------------------------------------------------------------------------

const lines: string[] = [];

lines.push(`# Stratum 1 — ${stratum.title}`);
lines.push('');
lines.push(`_${stratum.summary}_`);
lines.push('');
lines.push(
  '_Generated by `scripts/generate-stratum1-objectives.ts` from the same `@ogden/shared` ' +
    'catalogue data the live Plan/Act spine consumes. Re-run after any catalogue edit._',
);
lines.push('');
lines.push(
  `**Totals:** ${s1.length} standalone Stratum 1 objectives across ${groups.length} groups ` +
    `(${universal.length} universal + ${s1.length - universal.length} type-specific).`,
);
lines.push('');

// Summary table.
lines.push('| Group | Objectives |');
lines.push('|---|--:|');
for (const g of groups) {
  lines.push(`| ${g.heading} | ${g.objectives.length} |`);
}
lines.push('');
lines.push('---');
lines.push('');

for (const g of groups) {
  lines.push(`## ${g.heading}`);
  lines.push('');

  for (const obj of g.objectives) {
    const ref = obj.ref ?? obj.id;
    lines.push(`### ${ref} — ${obj.title}`);
    lines.push('');
    lines.push(`- **Objective id:** \`${obj.id}\``);
    if (obj.shortTitle) lines.push(`- **Short title:** ${obj.shortTitle}`);
    lines.push(`- **Focused question:** ${obj.focusedQuestion}`);
    if (obj.completionGate) lines.push(`- **Completion gate:** ${obj.completionGate}`);
    if (obj.actHandoff) lines.push(`- **Act handoff:** ${obj.actHandoff}`);
    if (obj.scopeNotes) lines.push(`- **Scope notes:** ${obj.scopeNotes}`);
    lines.push('');

    // Tasks (checklist), grouped by decisionGroups where defined.
    lines.push('**Tasks**');
    lines.push('');

    const renderItem = (id: string) => {
      const item = obj.checklist.find((c) => c.id === id);
      if (!item) return;
      const opt = item.optional ? ' _(optional)_' : '';
      lines.push(`- ${item.label}${opt}`);
    };

    if (obj.decisionGroups && obj.decisionGroups.length) {
      const inGroup = new Set(obj.decisionGroups.flatMap((dg) => dg.itemIds));
      for (const dg of obj.decisionGroups) {
        lines.push(`- **${dg.label}**`);
        for (const itemId of dg.itemIds) {
          const item = obj.checklist.find((c) => c.id === itemId);
          if (!item) continue;
          const opt = item.optional ? ' _(optional)_' : '';
          lines.push(`  - ${item.label}${opt}`);
        }
      }
      const loose = obj.checklist.filter((c) => !inGroup.has(c.id));
      if (loose.length) {
        lines.push('- **Other**');
        for (const item of loose) {
          const opt = item.optional ? ' _(optional)_' : '';
          lines.push(`  - ${item.label}${opt}`);
        }
      }
    } else {
      for (const item of obj.checklist) {
        const opt = item.optional ? ' _(optional)_' : '';
        lines.push(`- ${item.label}${opt}`);
      }
    }
    lines.push('');
  }
}

lines.push('---');
lines.push('');
lines.push(
  '> Patch-injected checklist items contributed by secondary layers are not standalone ' +
    'objectives and are not shown here; they appear only inside their target objective in the ' +
    'fully-resolved-with-secondary set.',
);
lines.push('');

const report = lines.join('\n');

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, report, 'utf8');

console.log(
  `Wrote ${s1.length} Stratum 1 objectives (${groups.length} groups) to ${OUT_PATH}`,
);
for (const g of groups) {
  console.log(`  ${g.heading}: ${g.objectives.length}`);
}
