/**
 * Plant species catalog — hardiness, drainage, slope, spacing, yield, companions.
 *
 * Consumed by plantingAnalysis.ts to filter species by site conditions.
 * ~20 species covering trees, shrubs, vines, and ground covers common
 * to temperate regenerative agriculture (zones 3-9).
 */

export interface PlantSpeciesInfo {
  id: string;
  commonName: string;
  latinName: string;
  category: 'tree' | 'shrub' | 'vine' | 'ground_cover';
  hardinessRange: [number, number];
  drainageSuitability: string[];
  maxSlopeDeg: number;
  spacingM: { inRow: number; betweenRow: number };
  yieldEstimate: { perTreeKg: number; unit: string } | null;
  frostSensitivity: 'low' | 'medium' | 'high';
  waterDemand: 'low' | 'medium' | 'high';
  companions: string[];
  incompatible: string[];
  daysToMaturity: number;
  canopySpreadM: number;
}

/** Parse hardiness zone string (e.g. "6a", "5b") to numeric (3-10). */
export function parseHardinessZone(zone: string): number {
  const match = zone.match(/^(\d+)/);
  return match?.[1] ? parseInt(match[1], 10) : 6;
}

export const PLANT_SPECIES: PlantSpeciesInfo[] = [
  // ── Trees ──────────────────────────────────────────────────────────
  {
    id: 'hybrid_chestnut',
    commonName: 'Hybrid Chestnut',
    latinName: 'Castanea dentata \u00d7 mollissima',
    category: 'tree',
    hardinessRange: [4, 8],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 20,
    spacingM: { inRow: 9, betweenRow: 12 },
    yieldEstimate: { perTreeKg: 25, unit: 'kg nuts' },
    frostSensitivity: 'medium',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover', 'elderberry'],
    incompatible: ['black_walnut'],
    daysToMaturity: 2190,
    canopySpreadM: 10,
  },
  {
    id: 'black_walnut',
    commonName: 'Black Walnut',
    latinName: 'Juglans nigra',
    category: 'tree',
    hardinessRange: [4, 9],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 12, betweenRow: 15 },
    yieldEstimate: { perTreeKg: 30, unit: 'kg nuts' },
    frostSensitivity: 'low',
    waterDemand: 'medium',
    companions: ['clover'],
    incompatible: ['apple', 'blueberry', 'currant'],
    daysToMaturity: 3650,
    canopySpreadM: 14,
  },
  {
    id: 'hazelnut',
    commonName: 'Hazelnut',
    latinName: 'Corylus americana',
    category: 'shrub',
    hardinessRange: [3, 9],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained'],
    maxSlopeDeg: 20,
    spacingM: { inRow: 3, betweenRow: 5 },
    yieldEstimate: { perTreeKg: 4, unit: 'kg nuts' },
    frostSensitivity: 'low',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover', 'currant'],
    incompatible: [],
    daysToMaturity: 1095,
    canopySpreadM: 4,
  },
  {
    id: 'apple',
    commonName: 'Apple',
    latinName: 'Malus domestica',
    category: 'tree',
    hardinessRange: [3, 8],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 5, betweenRow: 7 },
    yieldEstimate: { perTreeKg: 70, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover', 'currant', 'elderberry'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1460,
    canopySpreadM: 6,
  },
  {
    id: 'pear',
    commonName: 'Pear',
    latinName: 'Pyrus communis',
    category: 'tree',
    hardinessRange: [4, 8],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 5, betweenRow: 7 },
    yieldEstimate: { perTreeKg: 55, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover', 'grape'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1460,
    canopySpreadM: 6,
  },
  {
    id: 'peach',
    commonName: 'Peach',
    latinName: 'Prunus persica',
    category: 'tree',
    hardinessRange: [5, 9],
    drainageSuitability: ['well drained'],
    maxSlopeDeg: 12,
    spacingM: { inRow: 5, betweenRow: 6 },
    yieldEstimate: { perTreeKg: 45, unit: 'kg fruit' },
    frostSensitivity: 'high',
    waterDemand: 'medium',
    companions: ['comfrey', 'strawberry', 'clover'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1095,
    canopySpreadM: 5,
  },
  {
    id: 'cherry',
    commonName: 'Sweet Cherry',
    latinName: 'Prunus avium',
    category: 'tree',
    hardinessRange: [5, 8],
    drainageSuitability: ['well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 6, betweenRow: 8 },
    yieldEstimate: { perTreeKg: 30, unit: 'kg fruit' },
    frostSensitivity: 'high',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1825,
    canopySpreadM: 7,
  },
  {
    id: 'pecan',
    commonName: 'Pecan',
    latinName: 'Carya illinoinensis',
    category: 'tree',
    hardinessRange: [5, 9],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 10,
    spacingM: { inRow: 12, betweenRow: 15 },
    yieldEstimate: { perTreeKg: 35, unit: 'kg nuts' },
    frostSensitivity: 'medium',
    waterDemand: 'high',
    companions: ['clover', 'comfrey'],
    incompatible: [],
    daysToMaturity: 2555,
    canopySpreadM: 12,
  },
  {
    id: 'persimmon',
    commonName: 'American Persimmon',
    latinName: 'Diospyros virginiana',
    category: 'tree',
    hardinessRange: [4, 9],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained'],
    maxSlopeDeg: 20,
    spacingM: { inRow: 6, betweenRow: 8 },
    yieldEstimate: { perTreeKg: 35, unit: 'kg fruit' },
    frostSensitivity: 'low',
    waterDemand: 'low',
    companions: ['comfrey', 'clover', 'elderberry'],
    incompatible: [],
    daysToMaturity: 2190,
    canopySpreadM: 8,
  },
  {
    id: 'pawpaw',
    commonName: 'Pawpaw',
    latinName: 'Asimina triloba',
    category: 'tree',
    hardinessRange: [5, 9],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 4, betweenRow: 5 },
    yieldEstimate: { perTreeKg: 12, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'medium',
    companions: ['comfrey', 'elderberry'],
    incompatible: [],
    daysToMaturity: 2190,
    canopySpreadM: 5,
  },

  // ── Shrubs ─────────────────────────────────────────────────────────
  {
    id: 'elderberry',
    commonName: 'Elderberry',
    latinName: 'Sambucus canadensis',
    category: 'shrub',
    hardinessRange: [3, 9],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained'],
    maxSlopeDeg: 25,
    spacingM: { inRow: 2, betweenRow: 3 },
    yieldEstimate: { perTreeKg: 6, unit: 'kg berries' },
    frostSensitivity: 'low',
    waterDemand: 'medium',
    companions: ['hybrid_chestnut', 'apple', 'comfrey', 'clover'],
    incompatible: [],
    daysToMaturity: 730,
    canopySpreadM: 3,
  },
  {
    id: 'blueberry',
    commonName: 'Blueberry',
    latinName: 'Vaccinium corymbosum',
    category: 'shrub',
    hardinessRange: [3, 7],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 1.5, betweenRow: 3 },
    yieldEstimate: { perTreeKg: 4, unit: 'kg berries' },
    frostSensitivity: 'medium',
    waterDemand: 'high',
    companions: ['strawberry', 'clover'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1095,
    canopySpreadM: 2,
  },
  {
    id: 'currant',
    commonName: 'Red/Black Currant',
    latinName: 'Ribes rubrum / nigrum',
    category: 'shrub',
    hardinessRange: [3, 7],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 1.5, betweenRow: 2.5 },
    yieldEstimate: { perTreeKg: 3, unit: 'kg berries' },
    frostSensitivity: 'low',
    waterDemand: 'medium',
    companions: ['hazelnut', 'apple', 'comfrey'],
    incompatible: ['black_walnut'],
    daysToMaturity: 730,
    canopySpreadM: 1.5,
  },
  {
    id: 'gooseberry',
    commonName: 'Gooseberry',
    latinName: 'Ribes uva-crispa',
    category: 'shrub',
    hardinessRange: [3, 8],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 15,
    spacingM: { inRow: 1.5, betweenRow: 2.5 },
    yieldEstimate: { perTreeKg: 4, unit: 'kg berries' },
    frostSensitivity: 'low',
    waterDemand: 'medium',
    companions: ['comfrey', 'clover'],
    incompatible: [],
    daysToMaturity: 730,
    canopySpreadM: 1.5,
  },

  // ── Vines ──────────────────────────────────────────────────────────
  {
    id: 'grape',
    commonName: 'Grape',
    latinName: 'Vitis vinifera / labrusca',
    category: 'vine',
    hardinessRange: [4, 9],
    drainageSuitability: ['well drained'],
    maxSlopeDeg: 20,
    spacingM: { inRow: 2, betweenRow: 3 },
    yieldEstimate: { perTreeKg: 8, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'low',
    companions: ['clover', 'comfrey'],
    incompatible: ['black_walnut'],
    daysToMaturity: 1095,
    canopySpreadM: 2,
  },
  {
    id: 'hardy_kiwi',
    commonName: 'Hardy Kiwi',
    latinName: 'Actinidia arguta',
    category: 'vine',
    hardinessRange: [4, 8],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 10,
    spacingM: { inRow: 3, betweenRow: 5 },
    yieldEstimate: { perTreeKg: 20, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'medium',
    companions: ['comfrey'],
    incompatible: [],
    daysToMaturity: 1460,
    canopySpreadM: 4,
  },

  // ── Ground Covers ──────────────────────────────────────────────────
  {
    id: 'strawberry',
    commonName: 'Strawberry',
    latinName: 'Fragaria \u00d7 ananassa',
    category: 'ground_cover',
    hardinessRange: [3, 9],
    drainageSuitability: ['well drained', 'moderately well drained'],
    maxSlopeDeg: 10,
    spacingM: { inRow: 0.3, betweenRow: 1 },
    yieldEstimate: { perTreeKg: 0.4, unit: 'kg fruit' },
    frostSensitivity: 'medium',
    waterDemand: 'high',
    companions: ['blueberry', 'peach', 'comfrey'],
    incompatible: ['black_walnut'],
    daysToMaturity: 365,
    canopySpreadM: 0.4,
  },
  {
    id: 'comfrey',
    commonName: 'Comfrey',
    latinName: 'Symphytum officinale',
    category: 'ground_cover',
    hardinessRange: [3, 9],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained', 'poorly drained'],
    maxSlopeDeg: 25,
    spacingM: { inRow: 0.6, betweenRow: 1 },
    yieldEstimate: null,
    frostSensitivity: 'low',
    waterDemand: 'low',
    companions: ['hybrid_chestnut', 'apple', 'pear', 'cherry', 'elderberry', 'hazelnut', 'persimmon', 'pawpaw', 'grape', 'gooseberry'],
    incompatible: [],
    daysToMaturity: 180,
    canopySpreadM: 0.6,
  },
  {
    id: 'clover',
    commonName: 'White Clover',
    latinName: 'Trifolium repens',
    category: 'ground_cover',
    hardinessRange: [3, 10],
    drainageSuitability: ['well drained', 'moderately well drained', 'somewhat poorly drained'],
    maxSlopeDeg: 30,
    spacingM: { inRow: 0.15, betweenRow: 0.3 },
    yieldEstimate: null,
    frostSensitivity: 'low',
    waterDemand: 'low',
    companions: ['hybrid_chestnut', 'apple', 'pear', 'black_walnut', 'hazelnut', 'elderberry', 'grape', 'blueberry'],
    incompatible: [],
    daysToMaturity: 90,
    canopySpreadM: 0.3,
  },
];

/** Lookup map for O(1) access by ID. */
export const SPECIES_BY_ID: Record<string, PlantSpeciesInfo> = Object.fromEntries(
  PLANT_SPECIES.map((s) => [s.id, s]),
);
