/**
 * PresentationShareDialog — token generator for the read-only share
 * surface (OLOS Observe Dashboard Spec §6.2). Lets the steward pick an
 * expiry bucket (7d / 30d / 90d / permanent), opt sections out, and
 * copy the resulting URL.
 *
 * Token is generated by `presentationShareStore.createShare` (WebCrypto
 * 24-byte URL-safe random string). The dialog persists immediately on
 * "Generate" so abandoning the modal still leaves the share in the
 * store — revoke via the Domain Detail / Project Home (deferred to a
 * later slice).
 *
 * URL is built relative to `window.location.origin` to keep parity with
 * any deployment domain (atlas.ogden.ag, localhost, preview branch).
 */

import { useState } from 'react';
import type {
  PresentationShareExpiry,
  PresentationShareSectionId,
} from '@ogden/shared';
import { usePresentationShareStore } from '../../../../store/presentationShareStore.js';
import css from './PresentationShareDialog.module.css';

interface Props {
  projectId: string;
  onClose: () => void;
}

const EXPIRY_OPTIONS: readonly {
  id: PresentationShareExpiry;
  label: string;
}[] = [
  { id: '7d', label: '7 days' },
  { id: '30d', label: '30 days' },
  { id: '90d', label: '90 days' },
  { id: 'permanent', label: 'Permanent' },
];

const SECTION_OPTIONS: readonly {
  id: PresentationShareSectionId;
  label: string;
}[] = [
  { id: 'site_overview', label: 'Site overview' },
  { id: 'current_conditions', label: 'Current conditions' },
  { id: 'ecological_trajectory', label: 'Ecological trajectory' },
  { id: 'evidence_library', label: 'Evidence library' },
];

function buildShareUrl(token: string): string {
  const origin =
    typeof window !== 'undefined' && window.location
      ? window.location.origin
      : '';
  return `${origin}/v3/observe/share/${token}`;
}

export default function PresentationShareDialog({ projectId, onClose }: Props) {
  const createShare = usePresentationShareStore((s) => s.createShare);

  const [expiry, setExpiry] = useState<PresentationShareExpiry>('30d');
  const [included, setIncluded] = useState<Set<PresentationShareSectionId>>(
    () => new Set(SECTION_OPTIONS.map((opt) => opt.id)),
  );
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copyStatus, setCopyStatus] = useState<string | null>(null);

  const toggleSection = (id: PresentationShareSectionId) => {
    setIncluded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        if (next.size === 1) return prev;
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const handleGenerate = () => {
    const sections = SECTION_OPTIONS.filter((opt) => included.has(opt.id)).map(
      (opt) => opt.id,
    );
    const share = createShare({
      projectId,
      expiry,
      sections: sections.length === SECTION_OPTIONS.length ? [] : sections,
    });
    setShareUrl(buildShareUrl(share.token));
    setCopyStatus(null);
  };

  const handleCopy = async () => {
    if (!shareUrl) return;
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(shareUrl);
        setCopyStatus('Copied');
      } else {
        setCopyStatus('Copy unavailable - select the URL manually');
      }
    } catch {
      setCopyStatus('Copy failed - select the URL manually');
    }
  };

  return (
    <div
      className={css.backdrop}
      role="dialog"
      aria-modal="true"
      aria-labelledby="presentation-share-title"
      onClick={onClose}
    >
      <div className={css.dialog} onClick={(e) => e.stopPropagation()}>
        <h2 id="presentation-share-title" className={css.title}>
          Share this presentation
        </h2>
        <p className={css.intro}>
          Generates a read-only link to the current Observe snapshot.
          Recipients see only the sections you include below.
        </p>

        <fieldset className={css.fieldset}>
          <legend className={css.legend}>Expiry</legend>
          <div className={css.chipRow}>
            {EXPIRY_OPTIONS.map((opt) => (
              <button
                key={opt.id}
                type="button"
                className={expiry === opt.id ? css.chipActive : css.chip}
                onClick={() => setExpiry(opt.id)}
                aria-pressed={expiry === opt.id}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </fieldset>

        <fieldset className={css.fieldset}>
          <legend className={css.legend}>Included sections</legend>
          <ul className={css.sectionsList}>
            {SECTION_OPTIONS.map((opt) => (
              <li key={opt.id} className={css.sectionItem}>
                <input
                  id={`share-section-${opt.id}`}
                  type="checkbox"
                  checked={included.has(opt.id)}
                  onChange={() => toggleSection(opt.id)}
                />
                <label htmlFor={`share-section-${opt.id}`}>{opt.label}</label>
              </li>
            ))}
          </ul>
        </fieldset>

        {shareUrl && (
          <div className={css.fieldset}>
            <span className={css.legend}>Share URL</span>
            <div className={css.linkRow}>
              <input
                className={css.linkInput}
                type="text"
                readOnly
                value={shareUrl}
                onFocus={(e) => e.currentTarget.select()}
                aria-label="Share URL"
              />
              <button
                type="button"
                className={css.copy}
                onClick={handleCopy}
              >
                Copy
              </button>
            </div>
            {copyStatus && (
              <span className={css.copyStatus}>{copyStatus}</span>
            )}
          </div>
        )}

        <div className={css.footer}>
          <button type="button" className={css.secondary} onClick={onClose}>
            Close
          </button>
          <button
            type="button"
            className={css.primary}
            onClick={handleGenerate}
          >
            {shareUrl ? 'Generate another' : 'Generate link'}
          </button>
        </div>
      </div>
    </div>
  );
}
