-- Migration 010: ai_outputs — persist server-generated narratives + design recommendations.
--
-- Generated by the narrative BullMQ worker after the SiteAssessmentWriter completes.
-- One project can have many ai_outputs over its lifetime (regenerations); the app
-- reads the latest row per (project_id, output_type) via ORDER BY generated_at DESC.
-- Shape mirrors the shared `AIOutput` Zod schema; jsonb content is the parsed
-- narrative text; structured fields (confidence, data_sources, caveat, needs_site_visit)
-- are denormalised so the route can return them without a parse step.

CREATE TABLE IF NOT EXISTS ai_outputs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id        UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  output_type       TEXT NOT NULL CHECK (output_type IN (
    'site_narrative', 'design_recommendation', 'risk_flag',
    'planting_guide', 'investor_summary', 'design_brief'
  )),
  content           TEXT NOT NULL,
  confidence        TEXT NOT NULL CHECK (confidence IN ('high', 'medium', 'low')),
  data_sources      TEXT[] NOT NULL DEFAULT '{}',
  caveat            TEXT,
  needs_site_visit  BOOLEAN NOT NULL DEFAULT false,
  model_id          TEXT NOT NULL,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_outputs_project_type_time
  ON ai_outputs (project_id, output_type, generated_at DESC);

COMMENT ON TABLE ai_outputs IS
  'Server-generated AI narratives + design recommendations. Populated by the narrative BullMQ worker after Tier-3 assessment write. Read latest-per-(project, type) via idx_ai_outputs_project_type_time.';
