/**
 * SectionScaffold — dev-facing placeholder for orphan section pages.
 *
 * The 30 numbered feature sections each get a generated `<Slug>Page.tsx`
 * via `apps/api/scripts/scaffold-section.ts`, but the *real* surface for
 * most sections lives in a different folder (e.g. §6 `climate-analysis`
 * → `features/climate/SolarClimateDashboard.tsx`). The generated page is
 * never registered in the router (`apps/web/src/routes/index.tsx`) and is
 * never imported by `features/navigation/taxonomy.ts`.
 *
 * Rather than delete these files (and break re-runs of the scaffold
 * script), each `<Slug>Page.tsx` renders this scaffold pointing at the
 * real surface. If a developer or AI agent ever lands here by mistake,
 * they get a clear breadcrumb to the working surface instead of a flat
 * "coming soon" string.
 *
 * NOT exported from any barrel. NOT user-facing. If you find yourself
 * mounting this in a route, you are probably looking at the wrong file —
 * read `taxonomy.ts` first.
 */

interface SectionScaffoldProps {
  section: number;
  slug: string;
  name: string;
  realSurface: string | readonly string[];
  notes?: string;
}

export function SectionScaffold({
  section,
  slug,
  name,
  realSurface,
  notes,
}: SectionScaffoldProps) {
  const surfaces = Array.isArray(realSurface) ? realSurface : [realSurface];
  return (
    <div
      data-section-id={section}
      data-section-slug={slug}
      style={{
        padding: '2rem',
        fontFamily: 'var(--font-mono, monospace)',
        fontSize: '0.875rem',
        lineHeight: 1.6,
        color: 'var(--color-text-secondary, #666)',
        background: 'var(--color-surface-muted, #f5f5f5)',
        border: '1px dashed var(--color-border-subtle, #ccc)',
        borderRadius: '0.5rem',
      }}
    >
      <strong>Section {section} — {name}</strong>
      <br />
      <span>This page is an orphan scaffold. The real surface lives at:</span>
      <ul style={{ marginTop: '0.5rem' }}>
        {surfaces.map((s) => (
          <li key={s}><code>{s}</code></li>
        ))}
      </ul>
      {notes ? <p style={{ marginTop: '0.5rem' }}>{notes}</p> : null}
      <p style={{ marginTop: '0.5rem', fontSize: '0.75rem' }}>
        This file is generated by <code>apps/api/scripts/scaffold-section.ts</code>{' '}
        and is not mounted in the router. See{' '}
        <code>apps/web/src/features/navigation/taxonomy.ts</code> for the canonical
        surface map.
      </p>
    </div>
  );
}

export default SectionScaffold;
