/**
 * replayEvidenceAudit — Phase G.2 reproducibility sweep.
 *
 * Re-runs `selectEvidenceFor(...)` over rows of `evidence_audit_log` and
 * asserts byte-identical output. Closes the F.4 deferred follow-up
 * ("Server-side replay tool for `evidence_audit_log` — given an
 * `input_hash`, recompute the selector and assert byte-identical
 * output — durability test, not gating").
 *
 * Catches three flavors of silent drift:
 *   1. Selector drift — a refactor that changes outputs.
 *   2. Hash-function drift — a change to `stableStringify` / `hashInputs`
 *      that invalidates historical hashes.
 *   3. Schema drift — a payload shape the selector no longer accepts.
 *
 * The tool is pure read-side: it never writes to `evidence_audit_log`.
 * It is also durability-only — not gating. Operator-run (or eventual
 * CI cron) sweep across rows newer than a given ISO timestamp.
 */

import type postgres from 'postgres';
import {
  selectEvidenceFor,
  hashInputs,
  stableStringify,
  type EvidenceDispatchInputs,
} from '@ogden/shared/evidence';

export type ReplayFailureReason =
  | 'hash-mismatch'
  | 'output-mismatch'
  | 'unknown-panel'
  | 'selector-threw';

export interface ReplayFailure {
  rowId: string;
  panelKey: string;
  reason: ReplayFailureReason;
  detail?: string;
}

export interface ReplayResult {
  totalRows: number;
  okRows: number;
  failRows: number;
  failures: ReplayFailure[];
}

interface AuditRow {
  id: string;
  panel_key: string;
  input_hash: string;
  input_payload: unknown;
  evidence_output: unknown;
}

// The 8 dispatch keys are the only valid `panel_key` values. Anything
// else (e.g. a future panel that was emitted by a newer build) becomes
// `unknown-panel` rather than a hard error so the sweep keeps going.
const KNOWN_PANEL_KEYS = new Set<EvidenceDispatchInputs['panelKey']>([
  'land-verdict',
  'decision-triad',
  'site-narrative',
  'water-storage',
  'three-ethics',
  'water-router',
  'capital-partner',
  'host-canopy-union',
]);

function isKnownPanelKey(
  key: string,
): key is EvidenceDispatchInputs['panelKey'] {
  return KNOWN_PANEL_KEYS.has(key as EvidenceDispatchInputs['panelKey']);
}

/**
 * Replays every row of `evidence_audit_log` with `created_at >= sinceIso`.
 *
 * For each row:
 *   1. Recompute `hashInputs(input_payload)` — must match `input_hash`.
 *   2. Re-run `selectEvidenceFor({ panelKey, inputs: input_payload })`.
 *   3. `stableStringify(recomputed)` must equal `stableStringify(stored)`.
 *
 * Returns a sweep summary; never throws on per-row mismatches.
 */
export async function replayEvidenceAuditSince(
  sql: postgres.Sql,
  sinceIso: string,
): Promise<ReplayResult> {
  const since = new Date(sinceIso);
  if (Number.isNaN(since.getTime())) {
    throw new Error(`Invalid --all-since date: ${sinceIso}`);
  }

  const rows = (await sql`
    SELECT id, panel_key, input_hash, input_payload, evidence_output
    FROM evidence_audit_log
    WHERE created_at >= ${since.toISOString()}
    ORDER BY created_at ASC
  `) as unknown as AuditRow[];

  const result: ReplayResult = {
    totalRows: rows.length,
    okRows: 0,
    failRows: 0,
    failures: [],
  };

  for (const row of rows) {
    try {
      const recomputedHash = await hashInputs(row.input_payload);
      if (recomputedHash !== row.input_hash) {
        result.failRows += 1;
        result.failures.push({
          rowId: row.id,
          panelKey: row.panel_key,
          reason: 'hash-mismatch',
          detail: `stored=${row.input_hash} recomputed=${recomputedHash}`,
        });
        continue;
      }

      if (!isKnownPanelKey(row.panel_key)) {
        result.failRows += 1;
        result.failures.push({
          rowId: row.id,
          panelKey: row.panel_key,
          reason: 'unknown-panel',
        });
        continue;
      }

      // The cast is safe because `panel_key` is now a known dispatch key
      // and we trust `input_payload` to match the selector's input shape
      // (it was generated by the same selector at emit time).
      const recomputed = selectEvidenceFor({
        panelKey: row.panel_key,
        inputs: row.input_payload,
      } as EvidenceDispatchInputs);

      if (recomputed === null) {
        result.failRows += 1;
        result.failures.push({
          rowId: row.id,
          panelKey: row.panel_key,
          reason: 'selector-threw',
          detail: 'selector returned null',
        });
        continue;
      }

      const expected = stableStringify(row.evidence_output);
      const actual = stableStringify(recomputed);
      if (expected !== actual) {
        result.failRows += 1;
        result.failures.push({
          rowId: row.id,
          panelKey: row.panel_key,
          reason: 'output-mismatch',
          detail: `bytes differ (expected ${expected.length} vs actual ${actual.length})`,
        });
        continue;
      }

      result.okRows += 1;
    } catch (e: unknown) {
      result.failRows += 1;
      result.failures.push({
        rowId: row.id,
        panelKey: row.panel_key,
        reason: 'selector-threw',
        detail: e instanceof Error ? e.message : String(e),
      });
    }
  }

  return result;
}
