/**
 * Renders a project's DiagnoseBrief as a self-contained markdown document
 * and triggers a browser download. Used by the StageHero "Download Brief"
 * action on /v3/project/:id/diagnose.
 */

import type { Project } from "../types.js";

export function renderDiagnoseBriefMarkdown(project: Project): string {
  const brief = project.diagnose;
  if (!brief) return `# ${project.name}\n\nNo land brief available.\n`;

  const lines: string[] = [];
  lines.push(`# ${project.name} — Land Brief`);
  if (brief.parcelCaption) lines.push(`_${brief.parcelCaption}_`);
  lines.push("");
  lines.push(`**Verdict:** ${brief.verdict.label} · ${brief.verdict.score}/100`);
  lines.push("");
  lines.push(brief.verdict.summary);
  lines.push("");

  lines.push("## Categories");
  lines.push("");
  for (const c of brief.categories) {
    lines.push(`### ${c.title} — ${c.statusLabel}`);
    lines.push(c.summary);
    if (c.metric) lines.push(`- **${c.metric.label}:** ${c.metric.value}`);
    lines.push(`> _What this means:_ ${c.meaning}`);

    const detail = brief.categoryDetails?.[c.id];
    if (detail) {
      lines.push("");
      lines.push(`**What's happening.** ${detail.whatsHappening}`);
      lines.push(`**What's wrong.** ${detail.whatsWrong}`);
      lines.push(`**What next.** ${detail.whatNext}`);
      if (detail.metrics?.length) {
        lines.push("");
        lines.push("Supporting metrics:");
        for (const m of detail.metrics) {
          const hint = m.hint ? ` _(${m.hint})_` : "";
          lines.push(`- **${m.label}:** ${m.value}${hint}`);
        }
      }
      if (detail.mapHint) lines.push(`\n_${detail.mapHint}_`);
    }
    lines.push("");
  }

  const renderInsightSection = (label: string, kind: "risk" | "opportunity" | "limitation") => {
    const items = brief.insights.filter((i) => i.kind === kind);
    if (!items.length) return;
    lines.push(`## ${label}`);
    lines.push("");
    for (const i of items) {
      lines.push(`- **${i.title}.** ${i.detail}`);
    }
    lines.push("");
  };
  renderInsightSection("Risks", "risk");
  renderInsightSection("Opportunities", "opportunity");
  renderInsightSection("Limitations", "limitation");

  lines.push("---");
  lines.push(`_Generated by Atlas on ${new Date().toISOString().slice(0, 10)}._`);
  lines.push("");
  return lines.join("\n");
}

export function downloadDiagnoseBrief(project: Project): void {
  const md = renderDiagnoseBriefMarkdown(project);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.shortLabel || project.id}-land-brief.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
